___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

# Exploratory Data Analysis Project (Part - 1) - Session - 3

<blockquote style="background: #f9f9f9;padding: 0.5em 10px;" class="">
<img src="https://docs.google.com/uc?id=1FOcuE9AkAqc0JU6dUly-cuoUg3bOp92H" class="img-fluid" width="200" height="85"> <h1>EDA for Car Price Prediction Model</h1>
</blockquote>

In [1]:
import pandas as pd
import numpy as np
import warnings 

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', 500)
pd.set_option('display.max_info_columns', 500)
pd.set_option('display.max_info_rows', 2000)
pd.set_option('display.expand_frame_repr', True)
pd.set_option('display.width', 2000)

warnings.filterwarnings("ignore")
warnings.warn("this will not show")

In [2]:
oto = pd.read_json("scout_car.json", orient = "records", lines = True)

In [3]:
oto.head()

url make_model                                   short_description body_type  price               vat         km registration         prev_owner  kW      hp                                     Type Previous Owners                        Next Inspection                      Inspection new                          Warranty                      Full Service   Non-smoking Vehicle null      Make         Model     Offer Number First Registration       Body Color      Paint Type           Body Color Original          Upholstery              Body Nr. of Doors Nr. of Seats      Model Code         Gearing Type    Displacement Cylinders          Weight  Drive chain                                   Fuel                                                               Consumption               CO2 Emission Emission Class                                                                                                                                                                                                                                                                                                     \nComfort & Convenience\n                                                                       \nEntertainment & Media\n                                                      \nExtras\n                                                                                                                                                                                                                                                                                 \nSafety & Security\n  \
0         https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e    Audi A1         Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770    VAT deductible  56,013 km      01/2016  2 previous owners NaN   66 kW  [, Used, , Diesel (Particulate Filter)]           \n2\n  [\n06/2021\n, \n99 g CO2/km (comb)\n]               [\nYes\n, \nEuro 6\n]           [\n, \n, \n4 (Green)\n]                          [\n, \n]              [\n, \n]   []  \nAudi\n  [\n, A1, \n]  [\nLR-062483\n]     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]           [\nMythosschwarz\n]  [\nCloth, Black\n]  [\n, Sedans, \n]      [\n5\n]      [\n5\n]  [\n0588/BDF\n]  [\n, Automatic, \n]  [\n1,422 cc\n]   [\n3\n]  [\n1,220 kg\n]  [\nfront\n]  [\n, Diesel (Particulate Filter), \n]  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]   [\n99 g CO2/km (comb)\n]   [\nEuro 6\n]  [Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                     [Bluetooth, Hands-free equipment, On-board computer, Radio]              [Alloy wheels, Catalytic Converter, Voice Control]                                          [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]   
1                                      https://www.autoscout24.com//offers/audi-a1-1-8-tfsi-sport-gasoline-red-b2547f8a-e83f-6237-e053-e250040a56df    Audi A1                                      1.8 TFSI sport    Sedans  14500  Price negotiable  80,000 km      03/2017               None NaN  141 kW                     [, Used, , Gasoline]             NaN                                    NaN                                 NaN                               NaN                               NaN                   NaN   []  \nAudi\n  [\n, A1, \n]              NaN     [\n, 2017, \n]    [\n, Red, \n]             NaN                           NaN   [\nCloth, Grey\n]

##  Now let's try to examine our dataframe (oto)

In [4]:
oto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 54 columns):
 #   Column                         Dtype  
---  ------                         -----  
 0   url                            object 
 1   make_model                     object 
 2   short_description              object 
 3   body_type                      object 
 4   price                          int64  
 5   vat                            object 
 6   km                             object 
 7   registration                   object 
 8   prev_owner                     object 
 9   kW                             float64
 10  hp                             object 
 11  Type                           object 
 12  Previous Owners                object 
 13  Next Inspection                object 
 14  Inspection new                 object 
 15  Warranty                       object 
 16  Full Service                   object 
 17  Non-smoking Vehicle            object 
 18  null  

In [5]:
oto.describe()

price   kW
count  15919.000000  0.0
mean   18019.896727  NaN
std     7386.169409  NaN
min       13.000000  NaN
25%    12850.000000  NaN
50%    16900.000000  NaN
75%    21900.000000  NaN
max    74600.000000  NaN

## Handling with Missing Values.

- **Identifying the amount of the Missing Values**

In [6]:
oto.shape[0]

15919

In [7]:
oto.isnull().sum()*100/oto.shape[0]

url                                0.000000
make_model                         0.000000
short_description                  0.288963
body_type                          0.376908
price                              0.000000
vat                               28.349771
km                                 0.000000
registration                       0.000000
prev_owner                        42.892141
kW                               100.000000
hp                                 0.000000
Type                               0.012564
Previous Owners                   41.711163
Next Inspection                   77.793831
Inspection new                    75.299956
Warranty                          34.047365
Full Service                      48.395000
Non-smoking Vehicle               54.915510
null                               0.000000
Make                               0.000000
Model                              0.000000
Offer Number                      19.944720
First Registration              

In [8]:
col_list = list(oto.columns)

In [9]:
col_list

['url',
 'make_model',
 'short_description',
 'body_type',
 'price',
 'vat',
 'km',
 'registration',
 'prev_owner',
 'kW',
 'hp',
 'Type',
 'Previous Owners',
 'Next Inspection',
 'Inspection new',
 'Warranty',
 'Full Service',
 'Non-smoking Vehicle',
 'null',
 'Make',
 'Model',
 'Offer Number',
 'First Registration',
 'Body Color',
 'Paint Type',
 'Body Color Original',
 'Upholstery',
 'Body',
 'Nr. of Doors',
 'Nr. of Seats',
 'Model Code',
 'Gearing Type',
 'Displacement',
 'Cylinders',
 'Weight',
 'Drive chain',
 'Fuel',
 'Consumption',
 'CO2 Emission',
 'Emission Class',
 '\nComfort & Convenience\n',
 '\nEntertainment & Media\n',
 '\nExtras\n',
 '\nSafety & Security\n',
 'description',
 'Emission Label',
 'Gears',
 'Country version',
 'Electricity consumption',
 'Last Service Date',
 'Other Fuel Types',
 'Availability',
 'Last Timing Belt Service Date',
 'Available from']

## Let's begin to implement EDA Process to all *columns*

> ### We'll begin with the variables which has high percentage of missing values(NaNs). 
> ### We can remove some of them. At the begining we can focus on the columns that have %35 precentage and higher of missing values.

In [10]:
def show_nans(oto, limit):
    missing = oto.isnull().sum()*100/oto.shape[0]
    return missing.loc[lambda x : x > limit]
show_nans(oto, 35)

prev_owner                        42.892141
kW                               100.000000
Previous Owners                   41.711163
Next Inspection                   77.793831
Inspection new                    75.299956
Full Service                      48.395000
Non-smoking Vehicle               54.915510
Paint Type                        36.258559
Model Code                        68.729192
Cylinders                         35.680633
Weight                            43.809285
Drive chain                       43.080596
Emission Label                    74.967021
Country version                   52.346253
Electricity consumption           99.139393
Last Service Date                 96.444500
Other Fuel Types                  94.472015
Availability                      96.011056
Last Timing Belt Service Date     99.899491
Available from                    98.291350
dtype: float64

- We can drop the columns which have 90 percentage or high of missing values.

- ``'Availability'``, ``'Available from'``, ``'Electricity consumption'``, ``'Last Service Date'``, ``'Last Timing Belt Service Date'``, ``'Other Fuel Types'``, ``'kW'``

In [11]:
drop_list1 = ['Availability','Available from','Electricity consumption','Last Service Date','Last Timing Belt Service Date',
         'Other Fuel Types','kW']

In [12]:
oto.drop(drop_list1, axis=1, inplace=True)

``'prev_owner'`` is very similar to ``'Previous Owners'``.  ``'Weight'`` and ``'Non-smoking Vehicle'`` are assumed that they don't have meaningful  effect on the result. So we can drop them all.

### ``"prev_owner"`` and ``"Previous Owners"``

In [13]:
oto[["prev_owner", "Previous Owners"]]

prev_owner                                                                            Previous Owners
0      2 previous owners                                                                                      \n2\n
1                   None                                                                                        NaN
2       1 previous owner                                                                                      \n1\n
3       1 previous owner                                                                                      \n1\n
4       1 previous owner                                                                                      \n1\n
...                  ...                                                                                        ...
15914               None                                                                                        NaN
15915   1 previous owner  [\n1\n, \n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (city), \n, 6.3 l/100 km (country), \n]
15916   1 previous owner                                                           [\n1\n, \n139 g CO2/km (comb)\n]
15917               None                                                                                        NaN
15918   1 previous owner                                                                                      \n1\n

[15919 rows x 2 columns]

#### These two columns are very similar to each other. Let's choose better of them.

In [14]:
oto["Previous Owners"]

0                                                                                            \n2\n
1                                                                                              NaN
2                                                                                            \n1\n
3                                                                                            \n1\n
4                                                                                            \n1\n
                                                   ...                                            
15914                                                                                          NaN
15915    [\n1\n, \n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (city), \n, 6.3 l/100 km (country), \n]
15916                                                             [\n1\n, \n139 g CO2/km (comb)\n]
15917                                                                                          NaN
15918     

In [15]:
oto["prev_owner"]

0        2 previous owners
1                     None
2         1 previous owner
3         1 previous owner
4         1 previous owner
               ...        
15914                 None
15915     1 previous owner
15916     1 previous owner
15917                 None
15918     1 previous owner
Name: prev_owner, Length: 15919, dtype: object

In [16]:
oto["Previous Owners"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


\n1\n                                                                                        8101
NaN                                                                                          6640
\n2\n                                                                                         766
\n0\n                                                                                         163
\n3\n                                                                                          17
                                                                                             ... 
[\n1\n, \n96 g CO2/km (comb)\n]                                                                 1
[\n1\n, \n181 g CO2/km (comb)\n]                                                                1
[\n1\n, \n, 5.9 l/100 km (comb), \n, 7.9 l/100 km (city), \n, 4.8 l/100 km (country), \n]       1
[\n1\n, \n, 6.7 l/100 km (comb), \n, 8.6 l/100 km (city), \n, 5.6 l/100 km (country), \n]       1
[\n1\n, \n102 g CO2/

In [17]:
oto["prev_owner"].value_counts(dropna = False)

1 previous owner     8294
NaN                  6828
2 previous owners     778
3 previous owners      17
4 previous owners       2
Name: prev_owner, dtype: int64

### ``'Previous Owners'``

In [18]:
oto["Previous Owners"].str.strip("\n")

0          2
1        NaN
2          1
3          1
4          1
        ... 
15914    NaN
15915    NaN
15916    NaN
15917    NaN
15918      1
Name: Previous Owners, Length: 15919, dtype: object

In [19]:
oto["Previous Owners"].str.strip("\n").value_counts(dropna = False)

1      8101
NaN    6870
2       766
0       163
3        17
4         2
Name: Previous Owners, dtype: int64

In [20]:
oto["Previous Owners"].str[0]

0           \n
1          NaN
2           \n
3           \n
4           \n
         ...  
15914      NaN
15915    \n1\n
15916    \n1\n
15917      NaN
15918       \n
Name: Previous Owners, Length: 15919, dtype: object

In [21]:
oto['Previous Owners'].str[0].str[1]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ... 
15914    NaN
15915      1
15916      1
15917    NaN
15918    NaN
Name: Previous Owners, Length: 15919, dtype: object

In [22]:
oto['Previous Owners'].str[0].str[1].value_counts(dropna = False)

NaN    15689
1        193
0         25
2         12
Name: Previous Owners, dtype: int64

> ### We catch the values inside the lists.

> ### There are 230 new values which are not visible in previous format.

1   →     193

0   →     25

2   →     12

In [23]:
oto["Previous_Owner1"] = oto['Previous Owners'].str[0].str[1]
oto["Previous_Owner1"]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ... 
15914    NaN
15915      1
15916      1
15917    NaN
15918    NaN
Name: Previous_Owner1, Length: 15919, dtype: object

In [24]:
oto['Previous_Owner'] = oto['Previous Owners'].str.strip('\n')
oto['Previous_Owner']

0          2
1        NaN
2          1
3          1
4          1
        ... 
15914    NaN
15915    NaN
15916    NaN
15917    NaN
15918      1
Name: Previous_Owner, Length: 15919, dtype: object

In [25]:
oto.Previous_Owner.fillna(oto.Previous_Owner1, inplace=True)
oto.Previous_Owner.value_counts(dropna=False) 

1      8294
NaN    6640
2       778
0       188
3        17
4         2
Name: Previous_Owner, dtype: int64

### ``"Previous_Owner"`` our new column. Now, we have to fillna this column in the most convenient way

### We can fill the missing values with proportion of other existing values using `bfill` method.

In [26]:
oto["Previous_Owner"].fillna(method='bfill', inplace=True) 

In [27]:
oto["Previous_Owner"].value_counts(dropna = False)

1    14169
2     1179
0      531
3       38
4        2
Name: Previous_Owner, dtype: int64

### ``"prev_owner"``

In [28]:
oto.prev_owner.value_counts(dropna = False)

1 previous owner     8294
NaN                  6828
2 previous owners     778
3 previous owners      17
4 previous owners       2
Name: prev_owner, dtype: int64

In [29]:
oto["prev_owner"] = oto["prev_owner"].str.replace(" previous owner", "").str.replace("s", "")

In [30]:
oto.prev_owner.value_counts(dropna = False)

1      8294
NaN    6828
2       778
3        17
4         2
Name: prev_owner, dtype: int64

In [31]:
oto["prev_owner"].fillna(method='bfill', inplace=True)

In [32]:
oto.prev_owner.value_counts(dropna = False)

1    14692
2     1187
3       38
4        2
Name: prev_owner, dtype: int64

In [33]:
oto["Previous_Owner"].value_counts()

1    14169
2     1179
0      531
3       38
4        2
Name: Previous_Owner, dtype: int64

**It's better to drop ``"prev_owner"`` column in order to benefit more from ``"Previous_Owner"``. By the way, It is time to drop the other useless columns : `"Weight"`, `'Non-smoking Vehicle'`.**

In [34]:
drop_list2 = ["prev_owner", 'Weight','Non-smoking Vehicle']

In [35]:
oto.drop(drop_list2, axis = 1, inplace = True)

### ``'body_type'`` is also very similar to ``'Body'``.

- **Defining a Function**

In [36]:
def fill_most(oto, group_col, col_name):
    for group in list(oto[group_col].unique()) :
        grp_inx = list(oto[oto[group_col] == group][col_name].index)
        oto[col_name].iloc[grp_inx] = oto[col_name].iloc[grp_inx].fillna(oto[oto[group_col] == group][col_name].mode()[0])

In [37]:
#fill_most(oto, "make_model", "body_type")

In [38]:
#fill_most(oto, "make_model", "Extras")

In [39]:
#fill_most(oto, "make_model", "Comfort&Convenience")

In [40]:
#oto["make_model"].unique()

In [41]:
#oto["body_type"].iloc[grp_inx]

In [42]:
oto[oto["make_model"] == "Audi A3"]["body_type"]

2615      Convertible
2616           Sedans
2617           Sedans
2618           Sedans
2619           Sedans
            ...      
5707           Sedans
5708           Sedans
5709    Station wagon
5710           Sedans
5711           Sedans
Name: body_type, Length: 3097, dtype: object

In [43]:
grp_inx = list(oto[oto["make_model"] == "Audi A3"]["body_type"].index)

In [44]:
grp_inx

[2615,
 2616,
 2617,
 2618,
 2619,
 2620,
 2621,
 2622,
 2623,
 2624,
 2625,
 2626,
 2627,
 2628,
 2629,
 2630,
 2631,
 2632,
 2633,
 2634,
 2635,
 2636,
 2637,
 2638,
 2639,
 2640,
 2641,
 2642,
 2643,
 2644,
 2645,
 2646,
 2647,
 2648,
 2649,
 2650,
 2651,
 2652,
 2653,
 2654,
 2655,
 2656,
 2657,
 2658,
 2659,
 2660,
 2661,
 2662,
 2663,
 2664,
 2665,
 2666,
 2667,
 2668,
 2669,
 2670,
 2671,
 2672,
 2673,
 2674,
 2675,
 2676,
 2677,
 2678,
 2679,
 2680,
 2681,
 2682,
 2683,
 2684,
 2685,
 2686,
 2687,
 2688,
 2689,
 2690,
 2691,
 2692,
 2693,
 2694,
 2695,
 2696,
 2697,
 2698,
 2699,
 2700,
 2701,
 2702,
 2703,
 2704,
 2705,
 2706,
 2707,
 2708,
 2709,
 2710,
 2711,
 2712,
 2713,
 2714,
 2715,
 2716,
 2717,
 2718,
 2719,
 2720,
 2721,
 2722,
 2723,
 2724,
 2725,
 2726,
 2727,
 2728,
 2729,
 2730,
 2731,
 2732,
 2733,
 2734,
 2735,
 2736,
 2737,
 2738,
 2739,
 2740,
 2741,
 2742,
 2743,
 2744,
 2745,
 2746,
 2747,
 2748,
 2749,
 2750,
 2751,
 2752,
 2753,
 2754,
 2755,
 2756,
 2757,

In [45]:
oto["body_type"].iloc[2680]

'Sedans'

In [46]:
# oto[col_name].iloc[grp_inx] = oto[col_name].iloc[grp_inx].fillna()

In [47]:
# oto[oto["make_model"] == "Audi A3"]["body_type"].fillna("Sedans")

In [48]:
oto[oto["make_model"] == "Audi A3"]["body_type"].mode()[0]

'Sedans'

In [49]:
oto[oto["make_model"] == "Audi A1"]["body_type"].mode()[0]

'Sedans'

In [50]:
oto[oto["make_model"] == "Renault Espace"]["body_type"].mode()[0]

'Van'

***
***

### ``'body_type'``

In [51]:
oto["body_type"].value_counts(dropna = False)

Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

In [52]:
oto.groupby("make_model")["body_type"].value_counts(dropna = False)

make_model      body_type    
Audi A1         Sedans           1538
                Compact          1039
                Station wagon      21
                Other              13
                Coupe               2
                Van                 1
Audi A2         Off-Road            1
Audi A3         Sedans           2598
                Station wagon     282
                Compact           182
                Other              16
                Convertible         8
                NaN                 7
                Coupe               4
Opel Astra      Station wagon    1211
                Sedans           1053
                Compact           185
                Other              67
                NaN                 7
                Coupe               2
                Off-Road            1
Opel Corsa      Compact          1230
                Sedans            875
                Other              87
                Coupe              13
                Tran

In [53]:
fill_most(oto, "make_model", "body_type")

In [54]:
oto.body_type.value_counts(dropna = False)

Sedans           7925
Station wagon    3563
Compact          3155
Van               809
Other             290
Transporter        88
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

### ``"Body"``

In [55]:
oto["Body"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n, Sedans, \n]           7903
[\n, Station wagon, \n]    3553
[\n, Compact, \n]          3153
[\n, Van, \n]               783
[\n, Other, \n]             290
[\n, Transporter, \n]        88
NaN                          60
[\n, Off-Road, \n]           56
[\n, Coupe, \n]              25
[\n, Convertible, \n]         8
Name: Body, dtype: int64

### It seems that ``"Body"`` deserves to be dropped

In [56]:
oto.drop("Body", axis = 1, inplace = True)

***

### ``'Inspection new'``

In [57]:
oto["Inspection new"].isnull().sum()/len(oto["Inspection new"])

0.7529995602738866

#### It has high percentage of missing values, but it is important feature for the result (predicting price). We should keep it for now and we can assume missing values as 'no',  so that we can fillna missing values with string ``'no'``.

In [58]:
oto["Inspection new"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                                                                                            11987
[\nYes\n, \nEuro 6\n]                                                                            523
\nYes\n                                                                                          362
[\nYes\n, \n102 g CO2/km (comb)\n]                                                               174
[\nYes\n, \n4 (Green)\n]                                                                         166
                                                                                               ...  
[\nYes\n, \n, 6 l/100 km (comb), \n, 7.5 l/100 km (city), \n, 5.2 l/100 km (country), \n]          1
[\nYes\n, \n, 7 l/100 km (comb), \n, 9.5 l/100 km (city), \n, 5.5 l/100 km (country), \n]          1
[\nYes\n, \n174 g CO2/km (comb)\n]                                                                 1
[\nYes\n, \n, 5.9 l/100 km (comb), \n, 7.5 l/100 km (city), \n, 4.9 l/100 km (country), \n]

In [59]:
oto['Inspection new'].str[0].value_counts(dropna = False)

NaN        11987
\nYes\n     3570
\n           362
Name: Inspection new, dtype: int64

#### We chose the ``'\n'`` string in ``'.contains()'``. So we cover both variables in the lists and out of the lists
#### ``'*'`` 1 → gives us 1 or 0 according to True/False

In [60]:
oto['Inspection new'].str[0].str.contains("\n", na = False)

0         True
1        False
2        False
3        False
4         True
         ...  
15914    False
15915    False
15916     True
15917    False
15918     True
Name: Inspection new, Length: 15919, dtype: bool

In [61]:
True * 1

1

In [62]:
False * 1

0

In [63]:
oto["Inspection_New_Bool"] = oto['Inspection new'].str[0].str.contains("\n", na = False)*1

In [64]:
oto["Inspection_New_Bool"].value_counts(dropna = False)

0    11987
1     3932
Name: Inspection_New_Bool, dtype: int64

***

### ``'Next Inspection'``

In [65]:
oto['Next Inspection'].isnull().sum()/len(oto['Next Inspection'])

0.7779383127080847

In [66]:
oto["Next Inspection"]

0         [\n06/2021\n, \n99 g CO2/km (comb)\n]
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN
                          ...                  
15914                                       NaN
15915    [\n01/2022\n, \n168 g CO2/km (comb)\n]
15916                                       NaN
15917                                       NaN
15918                                       NaN
Name: Next Inspection, Length: 15919, dtype: object

In [67]:
oto["Next Inspection"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                                                                                              12384
\n04/2022\n                                                                                         62
\n03/2021\n                                                                                         38
\n03/2022\n                                                                                         36
\n06/2021\n                                                                                         34
                                                                                                 ...  
[\n08/2021\n, \n108 g CO2/km (comb)\n]                                                               1
[\n10/2019\n, \n, 5.3 l/100 km (comb), \n, 7 l/100 km (city), \n, 4.3 l/100 km (country), \n]        1
[\n11/2020\n, \n0 kWh/100 km (comb)\n]                                                               1
[\n10/2020\n, \n122 g CO2/km (comb)\n]                                   

In [68]:
a = ["I am a list"]

In [69]:
type(a) == list

True

In [70]:
"".join(a).strip()

'I am a list'

In [71]:
nxtins_list = ["".join(item).strip() if type(item) == list else item for item in oto['Next Inspection']]
oto['next_inspection'] = pd.DataFrame(nxtins_list)

In [72]:
oto.next_inspection.value_counts(dropna = False)

NaN                                                                          12384
\n04/2022\n                                                                     62
\n03/2021\n                                                                     38
\n03/2022\n                                                                     36
\n06/2021\n                                                                     34
                                                                             ...  
08/2021\n\n92 g CO2/km (comb)                                                    1
11/2019\n\n128 g CO2/km (comb)                                                   1
01/2020\n\n6.1 l/100 km (comb)\n8 l/100 km (city)\n5.1 l/100 km (country)        1
11/2019\n\n120 g CO2/km (comb)                                                   1
12/2021\n\n120 g CO2/km (comb)                                                   1
Name: next_inspection, Length: 1400, dtype: int64

In [73]:
oto["next_inspection"] = oto.next_inspection.str.extract("(\d\d/\d\d\d\d)")

In [74]:
oto.next_inspection.value_counts(dropna = False)

NaN        12384
06/2021      471
03/2021      210
05/2021      180
04/2021      171
           ...  
05/2014        1
01/1999        1
05/2017        1
01/1921        1
11/2022        1
Name: next_inspection, Length: 78, dtype: int64

In [75]:
oto.next_inspection = pd.to_datetime(oto.next_inspection, format = "%m/%Y")

In [76]:
oto.next_inspection.value_counts(dropna=False)

NaT           12384
2021-06-01      471
2021-03-01      210
2021-05-01      180
2021-04-01      171
              ...  
2016-04-01        1
1955-01-01        1
1999-01-01        1
2017-05-01        1
2016-05-01        1
Name: next_inspection, Length: 78, dtype: int64

### `"next_inspection"` has %77 percent of missing value. For now, let's leave it as it is. We can take a look at it again later.

### ``'Paint Type'``

In [77]:
oto["Paint Type"].isnull().sum()/len(oto["Paint Type"])*100

36.25855895470821

In [78]:
oto["Paint Type"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\nMetallic\n]       9794
NaN                  5772
[\nUni/basic\n]       347
[\nPerl effect\n]       6
Name: Paint Type, dtype: int64

In [79]:
oto["Paint Type"].str[0]

0        \nMetallic\n
1                 NaN
2        \nMetallic\n
3        \nMetallic\n
4        \nMetallic\n
             ...     
15914    \nMetallic\n
15915    \nMetallic\n
15916             NaN
15917             NaN
15918    \nMetallic\n
Name: Paint Type, Length: 15919, dtype: object

In [80]:
oto["Paint Type"].str[0].str.strip("\n").value_counts(dropna = False)

Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
Name: Paint Type, dtype: int64

### We should decide or specify its importance or value level for price prediction.

In [81]:
oto['paint_type'] = oto['Paint Type'].str[0].str.strip('\n')

In [82]:
oto['paint_type'].value_counts(dropna = False)

Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
Name: paint_type, dtype: int64

***

### ``'Country version'``

In [83]:
oto["Country version"].isnull().sum()/len(oto["Country version"])

0.5234625290533325

### It seems more than half of the data are missing.

In [84]:
oto["Country version"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                     8333
[\nGermany\n]           4502
[\nItaly\n]             1038
[\nEuropean Union\n]     507
[\nNetherlands\n]        464
[\nSpain\n]              325
[\nBelgium\n]            314
[\nAustria\n]            208
[\nCzech Republic\n]      52
[\nPoland\n]              49
[\nFrance\n]              38
[\nDenmark\n]             33
[\nHungary\n]             28
[\nJapan\n]                8
[\nSlovakia\n]             4
[\nCroatia\n]              4
[\nSweden\n]               3
[\nRomania\n]              2
[\nBulgaria\n]             2
[\nSerbia\n]               1
[\nLuxembourg\n]           1
[\nSwitzerland\n]          1
[\nSlovenia\n]             1
[\nEgypt\n]                1
Name: Country version, dtype: int64

In [85]:
oto['Country version'].str[0].str.strip('\n').value_counts(dropna=False) 

NaN               8333
Germany           4502
Italy             1038
European Union     507
Netherlands        464
Spain              325
Belgium            314
Austria            208
Czech Republic      52
Poland              49
France              38
Denmark             33
Hungary             28
Japan                8
Slovakia             4
Croatia              4
Sweden               3
Bulgaria             2
Romania              2
Serbia               1
Switzerland          1
Luxembourg           1
Egypt                1
Slovenia             1
Name: Country version, dtype: int64

### It's not essential for the result (price) but we can keep it.
### May be we can fillna using weight-mean in terms of values respectively

In [86]:
oto['country'] = oto['Country version'].str[0].str.strip('\n')

***

### ``'Cylinders'``

In [87]:
oto.Cylinders.isnull().sum()/len(oto.Cylinders)

0.3568063320560337

In [88]:
oto.Cylinders.value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n4\n]    8105
NaN        5680
[\n3\n]    2104
[\n5\n]      22
[\n6\n]       3
[\n2\n]       2
[\n8\n]       2
[\n1\n]       1
Name: Cylinders, dtype: int64

In [89]:
oto['Cylinders'].str[0].str.strip('\n').value_counts(dropna=False) 

4      8105
NaN    5680
3      2104
5        22
6         3
2         2
8         2
1         1
Name: Cylinders, dtype: int64

### We can handle with the missing values later. Let's keep it for now.

In [90]:
oto['Cylinders'] = oto['Cylinders'].str[0].str.strip('\n')

***

### ``'Emission Label'``

In [91]:
oto['Emission Label'].isnull().sum()/len(oto['Emission Label'])

0.749670205414913

### It has very high percentage of missing values. The percent of the missing values is high enough to drop but let's keep it for now.

In [92]:
oto["Emission Label"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                     11934
[\n4 (Green)\n]          3553
[\n1 (No sticker)\n]      381
[[], [], []]               40
[\n5 (Blue)\n]              8
[\n3 (Yellow)\n]            2
[\n2 (Red)\n]               1
Name: Emission Label, dtype: int64

In [93]:
oto['Emission Label'].str[0].str.strip('\n').value_counts(dropna=False) 

NaN               11974
4 (Green)          3553
1 (No sticker)      381
5 (Blue)              8
3 (Yellow)            2
2 (Red)               1
Name: Emission Label, dtype: int64

In [94]:
oto['emission_label'] = oto['Emission Label'].str[0].str.strip('\n')

In [95]:
oto.emission_label.value_counts(dropna = False)

NaN               11974
4 (Green)          3553
1 (No sticker)      381
5 (Blue)              8
3 (Yellow)            2
2 (Red)               1
Name: emission_label, dtype: int64

***

### ``'Full Service'``

In [96]:
oto['Full Service'].isnull().sum()/len(oto['Full Service'])*100

48.394999685909916

In [97]:
oto['Full Service'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                                                                                           7704
[\n, \n, \n4 (Green)\n]                                                                       2235
[\n, \n, \nEuro 6\n]                                                                          2097
[\n, \n]                                                                                      1702
[\n, \n, \nEuro 6d-TEMP\n]                                                                     399
                                                                                              ... 
[\n, \n, \n, 4.3 l/100 km (comb), \n, 5.2 l/100 km (city), \n, 3.9 l/100 km (country), \n]       1
[\n, \n, \n, 4.6 l/100 km (comb), \n, 5.8 l/100 km (city), \n, 3.9 l/100 km (country), \n]       1
[\n, \n, \nEuro 4\n]                                                                             1
[\n, \n, \n, 6.6 l/100 km (comb), \n, 8.4 l/100 km (city), \n, 5.6 l/100 km (country), \n]       1
[\n, \n, \

In [98]:
list(oto['Full Service'].value_counts(dropna=False).index)

[nan,
 ['\n', '\n', '\n4 (Green)\n'],
 ['\n', '\n', '\nEuro 6\n'],
 ['\n', '\n'],
 ['\n', '\n', '\nEuro 6d-TEMP\n'],
 '\n',
 ['\n', '\n', '\n120 g CO2/km (comb)\n'],
 ['\n', '\n', '\n126 g CO2/km (comb)\n'],
 ['\n', '\n', '\n104 g CO2/km (comb)\n'],
 ['\n', '\n', '\n97 g CO2/km (comb)\n'],
 ['\n', '\n', '\n124 g CO2/km (comb)\n'],
 ['\n', '\n', '\n99 g CO2/km (comb)\n'],
 ['\n', '\n', '\n128 g CO2/km (comb)\n'],
 ['\n', '\n', '\n119 g CO2/km (comb)\n'],
 ['\n', '\n', '\n140 g CO2/km (comb)\n'],
 ['\n', '\n', '\n106 g CO2/km (comb)\n'],
 ['\n', '\n', '\n92 g CO2/km (comb)\n'],
 ['\n', '\n', '\n107 g CO2/km (comb)\n'],
 ['\n', '\n', '\n114 g CO2/km (comb)\n'],
 ['\n', '\n', '\n102 g CO2/km (comb)\n'],
 ['\n', '\n', '\n103 g CO2/km (comb)\n'],
 ['\n', '\n', '\n1 (No sticker)\n'],
 ['\n', '\n', '\nEuro 6c\n'],
 ['\n', '\n', '\n139 g CO2/km (comb)\n'],
 ['\n', '\n', '\n117 g CO2/km (comb)\n'],
 ['\n', '\n', '\n127 g CO2/km (comb)\n'],
 ['\n', '\n', '\n141 g CO2/km (comb)\n'],
 ['\n', '\n', 

In [99]:
oto.drop("Full Service", axis = 1, inplace = True)

***

### ``'Comfort & Convenience'``

In [100]:
oto["\nComfort & Convenience\n"]

0                                                                                                                                                                                               [Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]
1                                                                                                                                                                                                                                                                                                                                   [Air conditioning, Automatic climate control, Hill Holder, Leather steering wheel, Lumbar support, Parking assist system sensors rear, Power windows, Start-stop system

In [101]:
oto['\nComfort & Convenience\n'].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                                                                                                                                                                                                                                                                                                                                                                     920
[Air conditioning, Electrical side mirrors, Hill Holder, Power windows]                                                                                                                                                                                                                                                                                                 216
[Air conditioning, Electrical side mirrors, Power windows]                                                                                                                                                                                                                      

In [102]:
oto['\nComfort & Convenience\n'].value_counts(dropna = False).head(50)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    920
[Air conditioning, Electrical side mirrors, Hill Holder, Power windows]                                                                                                                                                                                                                                                                                                                                                                                                                                      

In [103]:
oto['\nComfort & Convenience\n'].value_counts(dropna = False).tail(50)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[Air conditioning, Automatic climate control, Cruise control, Electrically adjustable seats, Electrical side mirrors, Heated steering wheel, Hill Holder, Leather steering wheel, Lumbar support, Multi-function steering wheel, Navigation system, Power windows, Rain sensor, Seat heating, Seat ventilation]                                                                                                                                        1
[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Leather steering wheel, Multi-function steering wheel, Park Distance Control, Parking assist system sensors front, Parking assist system sensors rear, Split rear seats, Start-stop system]                                                                                                                                                            1
[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Electric tailgate, Hea

> ### May be this column contains the most important data for prediction of the price.
> ### Because there are some variables that have list in list, so we have to see all 'combined' values the variables have. 
> ### We have to examine the unique values. We produce two function to do that.  First we convert ``NaN`` values to empty list than combine all values using ``set().update()`` syntax.

In [104]:
# We can't operate with NaNs. We have to examine the unique values of this column.

#uni = set()
#uni.update(np.nan)
#uni.update(["a", "b", "a"])
#list(uni)

In [105]:
# The new version of this data is a string. We have to convert its elments backto the list type.
# In order to use .get_dummies() method, we have to do that.

#oto['Comfort&Convenience'][0]

- **Defining a Function**

In [106]:
def unique_values(data, column_name):
    unique_vals = set()
    for rows in data[column_name]:
        unique_vals.update(rows)
    return list(unique_vals)

In [107]:
nans = oto['\nComfort & Convenience\n'].isnull()

In [108]:
oto.loc[nans, '\nComfort & Convenience\n']

9        NaN
30       NaN
53       NaN
168      NaN
191      NaN
        ... 
15791    NaN
15804    NaN
15805    NaN
15854    NaN
15864    NaN
Name: \nComfort & Convenience\n, Length: 920, dtype: object

In [109]:
def Nan_to_list(data, column_name):
    NaN_rows = data[column_name].isnull()
    data.loc[NaN_rows, column_name] = data.loc[NaN_rows, column_name].apply(lambda x : [])

In [110]:
Nan_to_list(oto, '\nComfort & Convenience\n')
unique_values(oto, '\nComfort & Convenience\n')

['Parking assist system sensors front',
 'Rain sensor',
 'Panorama roof',
 'Electrically heated windshield',
 'Parking assist system camera',
 'Lumbar support',
 'Parking assist system self-steering',
 'Parking assist system sensors rear',
 'Split rear seats',
 'Electrical side mirrors',
 'Tinted windows',
 'Armrest',
 'Heads-up display',
 'Auxiliary heating',
 'Electric Starter',
 'Massage seats',
 'Cruise control',
 'Seat ventilation',
 'Sunroof',
 'Seat heating',
 'Electrically adjustable seats',
 'Multi-function steering wheel',
 'Automatic climate control',
 'Hill Holder',
 'Park Distance Control',
 'Light sensor',
 'Windshield',
 'Air conditioning',
 'Power windows',
 'Wind deflector',
 'Navigation system',
 'Leather seats',
 'Leather steering wheel',
 'Electric tailgate',
 'Heated steering wheel',
 'Air suspension',
 'Start-stop system',
 'Keyless central door lock']

In [111]:
nxtins_list = [",".join(item).strip() if type(item) == list else item for item in oto['\nComfort & Convenience\n']]

In [112]:
oto["Comfort&Convenience"] = pd.DataFrame(nxtins_list)

In [113]:
oto['Comfort&Convenience'].value_counts(dropna=False)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                920
Air conditioning,Electrical side mirrors,Hill Holder,Power windows                                                                                                                                                                                                                                                                                                                                                                  

In [114]:
oto[oto['Comfort&Convenience'] == ""]

url      make_model                                  short_description body_type  price             vat          km registration      hp                  Type Previous Owners Next Inspection Inspection new       Warranty null         Make             Model    Offer Number First Registration       Body Color      Paint Type                   Body Color Original Upholstery Nr. of Doors Nr. of Seats Model Code         Gearing Type    Displacement Cylinders  Drive chain                Fuel                                                               Consumption               CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n      \nExtras\n \nSafety & Security\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          description Emission Label    Gears Country version Previous_Owner1 Previous_Owner  Inspection_New_Bool next_inspection paint_type country emission_label Comfort&Convenience
9                  https://www.autoscout24.com//offers/audi-a1-sportback-tfsi-ultra-95-s-tronic-amb-gasoline-white-e2c49a42-6aaa-4039-9af1-7546a20c110e         Audi A1              SPORTBACK TFSI ULTRA 95 S-TRONIC AMB.    Sedans  17990            None   16,103 km      06/2017   70 kW  [, Used, , Gasoline]             NaN             NaN            NaN   \n3 months\n   []     \nAudi\n      [\n, A1, \n]             NaN     [\n, 2017, \n]  [\n, White, \n]             NaN                           [\nBlanc\n]        NaN      [\n5\n]      [\n4\n]        NaN  [\n, Automatic, \n]    [\n999 cc\n]       NaN          NaN  [\n, Gasoline, \n]                                                                       NaN                        NaN            NaN                        []                       NaN             NaN                   NaN  [\nClim automatique,Ecran multifonction couleur,Capteur de pluie,Capteur de luminosité,Contrôle élect. de la pression des pneus,Régulateur de vitesse,EBD,ESP,8 Haut parleurs,ABS,Airbag conducteur,Airbag passager,Airbags latéraux avant,Airbags rideaux AV et AR,Antidémarrage électronique,Antipatinage,Appui-tête conducteur réglable hauteur,Appui-tête passager réglable en hauteur,Arrêt et redémarrage auto. du moteur,Bacs de portes avant,Banquette 1/3-2/3,Banquette AR rabattable,Boite à gant ferm...            NaN  [\n7\n]             NaN             NaN              1                    0             NaT        NaN     NaN            NaN                    
30                            https://www.autoscout24.com//offers/audi-a1-sportback-1-4tdi-attraction-diesel-black-be5e7705-5e6e-4ca0-a7df-fc6153d6e384         Audi A1                        Sportback 1.4TDI Attraction   Compact  11290            None   38,400 km      06/2016   66 kW    [, Used, , Diesel]             NaN             NaN            NaN  \n12 months\n   []     \nAudi\n      [\n, A1, \n]   [\n2780690\n]     [\n, 2016, \n]  [\n, Black, \n]             NaN                           [\nNegro\n]        NaN      [\n5\n]      [\n5\n]        NaN     [\n, Manual, \n]  [\n1,422 cc\n]         3  [\nfront\n]    [\n, Diesel, \n]        [[3 l/100 km (comb)], [3 l/100 km (city)], [3 l/100 km (country)]]                        NaN            NaN                        []                       NaN             NaN                   NaN  [\nVEHÍCULO NACIONAL, PROCEDE DE CONCESIONARIO OFICIAL , KMTS CERTIFICADOS CON LIBRO DE REVISIONES EN CONCESIONARIO OFICIAL, MUY BUEN ESTADO GENERAL Y MECANICO (21% IVA INCLUIDO EN EL PRECIO), AUX, SROP&GO, 5 PLAZAS, CIERRE CENTRALIZADO , ESPEJOS AUT..., ACEPTAMOS VEHICULO COMO PAGO , 

In [115]:
oto['Comfort&Convenience'].isnull().sum()

0

In [116]:
[np.nan if oto['Comfort&Convenience'].iloc[i] == "" else oto['Comfort&Convenience'].iloc[i] for i in range(len(oto['Comfort&Convenience']))] 

['Air conditioning,Armrest,Automatic climate control,Cruise control,Electrical side mirrors,Hill Holder,Leather steering wheel,Light sensor,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Start-stop system',
 'Air conditioning,Automatic climate control,Hill Holder,Leather steering wheel,Lumbar support,Parking assist system sensors rear,Power windows,Start-stop system,Tinted windows',
 'Air conditioning,Cruise control,Electrical side mirrors,Hill Holder,Leather steering wheel,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Seat heating,Start-stop system',
 'Air suspension,Armrest,Auxiliary heating,Electrical side mirrors,Heads-up display,Hill Holder,Leather steering wheel,Light sensor,Lumbar support,Multi-function steering wheel,Navigation system,Power windows,Rain sensor,Seat heating,Sp

In [117]:
oto["Comfort&Convenience"] = [np.nan if oto['Comfort&Convenience'].iloc[i] == "" else oto['Comfort&Convenience'].iloc[i] for i in range(len(oto['Comfort&Convenience']))]

In [118]:
oto["Comfort&Convenience"].value_counts(dropna = False)

NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             920
Air conditioning,Electrical side mirrors,Hill Holder,Power windows                                                                                                                                                                                                                                                                                                                                                                  

In [119]:
fill_most(oto, "make_model", "Comfort&Convenience")

In [120]:
oto['Comfort&Convenience'].isnull().sum()

0

In [121]:
oto['Comfort&Convenience'].value_counts()

Air conditioning,Electrical side mirrors,Hill Holder,Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              389
Air conditioning,Armrest,Automatic climate control,Cruise control,Electrically adjustable seats,Electrical side mirrors,Electric tailgate,Heated steering wheel,Hill Holder,Keyless central door lock,Leather steering wheel,Light sensor,Lumbar support,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system camera,Parking assist system sensors front,Parking assist system sensors rear,P

In [122]:
"Windshield" in oto["Comfort&Convenience"][0]

False

In [124]:
oto["Comfort&Convenience"].head()

0    Air conditioning,Armrest,Automatic climate control,Cruise control,Electrical side mirrors,Hill Holder,Leather steering wheel,Light sensor,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Start-stop system
1                                                                                                                                 Air conditioning,Automatic climate control,Hill Holder,Leather steering wheel,Lumbar support,Parking assist system sensors rear,Power windows,Start-stop system,Tinted windows
2                           Air conditioning,Cruise control,Electrical side mirrors,Hill Holder,Leather steering wheel,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Seat heating,Start-stop system
3                                     Air suspension,Armrest,Auxiliary heating,Electr

In [123]:
oto["Comfort&Convenience"].str.get_dummies(sep = ",")

Air conditioning  Air suspension  Armrest  Automatic climate control  Auxiliary heating  Cruise control  Electric Starter  Electric tailgate  Electrical side mirrors  Electrically adjustable seats  Electrically heated windshield  Heads-up display  Heated steering wheel  Hill Holder  Keyless central door lock  Leather seats  Leather steering wheel  Light sensor  Lumbar support  Massage seats  Multi-function steering wheel  Navigation system  Panorama roof  Park Distance Control  Parking assist system camera  Parking assist system self-steering  Parking assist system sensors front  Parking assist system sensors rear  Power windows  Rain sensor  Seat heating  Seat ventilation  Split rear seats  Start-stop system  Sunroof  Tinted windows  Wind deflector  Windshield
0                     1               0        1                          1                  0               1                 0                  0                        1                              0                               0                 0                      0            1                          0              0                       1             1               0              0                              1                  1              0                      1                             0                                    0                                    0                                   1              1            1             1                 0                 0                  1        0               0               0           0
1                     1               0        0                          1                  0               0                 0                  0                        0                              0                               0                 0                      0            1                          0              0                       1             0               1              0                              0                  0              0                      0                             0                                    0                                    0                                   1              1            0             0                 0                 0                  1        0               1               0           0
2                     1               0        0                          0                  0               1                 0                  0                        1                              0                               0                 0                      0            1                          0              0                       1             0               0              0                              1                  1              0                      1                             0                                    0                                    1                                   1              1            0             1                 0                 0                  1        0               0               0           0
3                     0               1        1                          0                  1               0                 0                  0                        1                              0                               0                 1                      0            1                          0              0                       1             1               1              0                              1                  1              0                      0                             0                                    0                                    0                                   0              1            1             1                 0                 1                  1        0               0               0           0
4                     1               0        1                          1                  0               0  

In [125]:
oto = oto.join(oto["Comfort&Convenience"].str.get_dummies(sep = ",").add_prefix("cc_"))

In [126]:
oto.head()

url make_model                                   short_description body_type  price               vat         km registration      hp                                     Type Previous Owners                        Next Inspection                      Inspection new                          Warranty null      Make         Model     Offer Number First Registration       Body Color      Paint Type           Body Color Original          Upholstery Nr. of Doors Nr. of Seats      Model Code         Gearing Type    Displacement Cylinders  Drive chain                                   Fuel                                                               Consumption               CO2 Emission Emission Class                                                                                                                                                                                                                                                                                                     \nComfort & Convenience\n                                                                       \nEntertainment & Media\n                                                      \nExtras\n                                                                                                                                                                                                                                                                                 \nSafety & Security\n  \
0         https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e    Audi A1         Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770    VAT deductible  56,013 km      01/2016   66 kW  [, Used, , Diesel (Particulate Filter)]           \n2\n  [\n06/2021\n, \n99 g CO2/km (comb)\n]               [\nYes\n, \nEuro 6\n]           [\n, \n, \n4 (Green)\n]   []  \nAudi\n  [\n, A1, \n]  [\nLR-062483\n]     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]           [\nMythosschwarz\n]  [\nCloth, Black\n]      [\n5\n]      [\n5\n]  [\n0588/BDF\n]  [\n, Automatic, \n]  [\n1,422 cc\n]         3  [\nfront\n]  [\n, Diesel (Particulate Filter), \n]  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]   [\n99 g CO2/km (comb)\n]   [\nEuro 6\n]  [Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                     [Bluetooth, Hands-free equipment, On-board computer, Radio]              [Alloy wheels, Catalytic Converter, Voice Control]                                          [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]   
1                                      https://www.autoscout24.com//offers/audi-a1-1-8-tfsi-sport-gasoline-red-b2547f8a-e83f-6237-e053-e250040a56df    Audi A1                                      1.8 TFSI sport    Sedans  14500  Price negotiable  80,000 km      03/2017  141 kW                     [, Used, , Gasoline]             NaN                                    NaN                                 NaN                               NaN   []  \nAudi\n  [\n, A1, \n]              NaN     [\n, 2017, \n]    [\n, Red, \n]             NaN                           NaN   [\nCloth, Grey\n]      [\n3\n]      [\n4\n]  [\n0588/BCY\n]  [\n, Automatic, \n]  [\n1,798 cc\n]         4  [\nfront\n]                     [\n, Gasoline, \n]  [[5.6 l/100 km (comb)], [7.1 l/100 km (city)], [4.7 l/100 km (country)]]  [\n129 g CO2/km (comb)\n]   [\nEuro 6\n]                                                

In [127]:
oto.shape

(15919, 88)

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

# Exploratory Data Analysis Project (Part - 1) - Session - 4

<blockquote style="background: #f9f9f9;padding: 0.5em 10px;" class="">
<img src="https://docs.google.com/uc?id=1FOcuE9AkAqc0JU6dUly-cuoUg3bOp92H" class="img-fluid" width="200" height="85"> <h1>EDA for Car Price Prediction Model</h1>
</blockquote>

***

### ``'\nEntertainment & Media\n'``

In [129]:
oto['\nEntertainment & Media\n'].isnull().sum()/len(oto['\nEntertainment & Media\n'])*100

8.63119542684842

In [130]:
oto['\nEntertainment & Media\n'].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                                                                                      1374
[Bluetooth, Hands-free equipment, On-board computer, Radio, USB]                         1282
[Bluetooth, Hands-free equipment, MP3, On-board computer, Radio, USB]                     982
[Bluetooth, CD player, Hands-free equipment, MP3, On-board computer, Radio, USB]          783
[On-board computer, Radio]                                                                487
                                                                                         ... 
[Bluetooth, MP3, On-board computer, Sound system, USB]                                      1
[CD player, Hands-free equipment, On-board computer, Radio, Sound system, Television]       1
[Bluetooth, Digital radio, On-board computer, Sound system, USB]                            1
[CD player, Hands-free equipment, MP3, Radio, USB]                                          1
[CD player, Digital radio, Radio]                           

In [131]:
oto['\nEntertainment & Media\n'][0]

['Bluetooth', 'Hands-free equipment', 'On-board computer', 'Radio']

In [132]:
",".join(oto['\nEntertainment & Media\n'][0])

'Bluetooth,Hands-free equipment,On-board computer,Radio'

In [133]:
Nan_to_list(oto, '\nEntertainment & Media\n')
unique_values(oto, '\nEntertainment & Media\n')

['Radio',
 'MP3',
 'Digital radio',
 'CD player',
 'Sound system',
 'Television',
 'Hands-free equipment',
 'USB',
 'Bluetooth',
 'On-board computer']

In [134]:
oto['\nEntertainment & Media\n'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[]                                                                                                           1374
[Bluetooth, Hands-free equipment, On-board computer, Radio, USB]                                             1282
[Bluetooth, Hands-free equipment, MP3, On-board computer, Radio, USB]                                         982
[Bluetooth, CD player, Hands-free equipment, MP3, On-board computer, Radio, USB]                              783
[On-board computer, Radio]                                                                                    487
                                                                                                             ... 
[CD player, Digital radio, Hands-free equipment, On-board computer, Radio, Sound system, Television, USB]       1
[Digital radio, MP3, On-board computer, Radio, Sound system, USB]                                               1
[Digital radio, Hands-free equipment, MP3, On-board computer, USB]                      

In [135]:
nxtins_list = [",".join(item).strip() if type(item) == list else item for item in oto['\nEntertainment & Media\n']]

In [136]:
nxtins_list

['Bluetooth,Hands-free equipment,On-board computer,Radio',
 'Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system',
 'MP3,On-board computer',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system,USB',
 'Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,Sound system,USB',
 'CD player,MP3,Radio',
 'Radio',
 '',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'CD player,Hands-free equipment,On-board computer,Radio,USB',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'Bluetooth,On-board computer,Radio',
 'Bluetooth,CD player,Hands-free equipment,On-board computer,Radio',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'CD player,MP3,Radio',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-

In [137]:
oto['Entertainment&Media'] = pd.DataFrame(nxtins_list)

In [138]:
oto['Entertainment&Media'].value_counts(dropna=False)

                                                                                                  1374
Bluetooth,Hands-free equipment,On-board computer,Radio,USB                                        1282
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,USB                                     982
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB                           783
On-board computer,Radio                                                                            487
                                                                                                  ... 
Bluetooth,Sound system,USB                                                                           1
Digital radio,On-board computer,USB                                                                  1
Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,Television,USB                      1
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Sound 

In [139]:
oto['Entertainment&Media'].isnull().sum()

0

In [140]:
[np.nan if oto['Entertainment&Media'].iloc[i] == "" else oto['Entertainment&Media'].iloc[i] for i in range(len(oto['Entertainment&Media']))]

['Bluetooth,Hands-free equipment,On-board computer,Radio',
 'Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system',
 'MP3,On-board computer',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system,USB',
 'Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,Sound system,USB',
 'CD player,MP3,Radio',
 'Radio',
 nan,
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'CD player,Hands-free equipment,On-board computer,Radio,USB',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'Bluetooth,On-board computer,Radio',
 'Bluetooth,CD player,Hands-free equipment,On-board computer,Radio',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'CD player,MP3,Radio',
 'Bluetooth,CD player,Hands-free equipment,MP3,On

In [141]:
oto['Entertainment&Media'] = [np.nan if oto['Entertainment&Media'].iloc[i] == "" else oto['Entertainment&Media'].iloc[i] for i in range(len(oto['Entertainment&Media']))]

In [142]:
fill_most(oto, "make_model", "Entertainment&Media")

In [143]:
oto['Entertainment&Media'].value_counts(dropna = False)

Bluetooth,Hands-free equipment,On-board computer,Radio,USB                                2015
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,USB                            1206
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB                  1049
Bluetooth,Hands-free equipment,On-board computer,Radio                                     529
On-board computer,Radio                                                                    487
                                                                                          ... 
Digital radio,On-board computer,USB                                                          1
Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,Television,USB              1
Bluetooth,Sound system,USB                                                                   1
Bluetooth,CD player,Hands-free equipment,On-board computer,Sound system,Television,USB       1
Bluetooth,Digital radio,On-board computer,Radio,Te

In [144]:
oto['Entertainment&Media'].str.get_dummies(sep = ",")

Bluetooth  CD player  Digital radio  Hands-free equipment  MP3  On-board computer  Radio  Sound system  Television  USB
0              1          0              0                     1    0                  1      1             0           0    0
1              1          0              0                     1    0                  1      1             1           0    0
2              0          0              0                     0    1                  1      0             0           0    0
3              1          1              0                     1    1                  1      1             1           0    1
4              1          1              0                     1    1                  1      1             0           0    1
...          ...        ...            ...                   ...  ...                ...    ...           ...         ...  ...
15914          1          0              1                     1    0                  1      1             0           0    1
15915          1          0              1                     1    0                  0      1             0           0    1
15916          1          0              0                     1    0                  1      1             0           0    0
15917          1          0              1                     0    0                  0      1             0           0    1
15918          0          0              0                     0    0                  0      0             0           0    1

[15919 rows x 10 columns]

In [145]:
oto = oto.join(oto['Entertainment&Media'].str.get_dummies(sep = ",").add_prefix("em_"))

In [146]:
oto.head()

url make_model                                   short_description body_type  price               vat         km registration      hp                                     Type Previous Owners                        Next Inspection                      Inspection new                          Warranty null      Make         Model     Offer Number First Registration       Body Color      Paint Type           Body Color Original          Upholstery Nr. of Doors Nr. of Seats      Model Code         Gearing Type    Displacement Cylinders  Drive chain                                   Fuel                                                               Consumption               CO2 Emission Emission Class                                                                                                                                                                                                                                                                                                     \nComfort & Convenience\n                                                                       \nEntertainment & Media\n                                                      \nExtras\n                                                                                                                                                                                                                                                                                 \nSafety & Security\n  \
0         https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e    Audi A1         Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770    VAT deductible  56,013 km      01/2016   66 kW  [, Used, , Diesel (Particulate Filter)]           \n2\n  [\n06/2021\n, \n99 g CO2/km (comb)\n]               [\nYes\n, \nEuro 6\n]           [\n, \n, \n4 (Green)\n]   []  \nAudi\n  [\n, A1, \n]  [\nLR-062483\n]     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]           [\nMythosschwarz\n]  [\nCloth, Black\n]      [\n5\n]      [\n5\n]  [\n0588/BDF\n]  [\n, Automatic, \n]  [\n1,422 cc\n]         3  [\nfront\n]  [\n, Diesel (Particulate Filter), \n]  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]   [\n99 g CO2/km (comb)\n]   [\nEuro 6\n]  [Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                     [Bluetooth, Hands-free equipment, On-board computer, Radio]              [Alloy wheels, Catalytic Converter, Voice Control]                                          [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]   
1                                      https://www.autoscout24.com//offers/audi-a1-1-8-tfsi-sport-gasoline-red-b2547f8a-e83f-6237-e053-e250040a56df    Audi A1                                      1.8 TFSI sport    Sedans  14500  Price negotiable  80,000 km      03/2017  141 kW                     [, Used, , Gasoline]             NaN                                    NaN                                 NaN                               NaN   []  \nAudi\n  [\n, A1, \n]              NaN     [\n, 2017, \n]    [\n, Red, \n]             NaN                           NaN   [\nCloth, Grey\n]      [\n3\n]      [\n4\n]  [\n0588/BCY\n]  [\n, Automatic, \n]  [\n1,798 cc\n]         4  [\nfront\n]                     [\n, Gasoline, \n]  [[5.6 l/100 km (comb)], [7.1 l/100 km (city)], [4.7 l/100 km (country)]]  [\n129 g CO2/km (comb)\n]   [\nEuro 6\n]                                                

***

### ``'\nExtras\n'``

In [147]:
oto['\nExtras\n'].isnull().sum()/len(oto['\nExtras\n'])*100

18.60669640052767

In [148]:
oto['\nExtras\n'].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[Alloy wheels]                                                                                         3245
NaN                                                                                                    2962
[Alloy wheels, Touch screen]                                                                            697
[Alloy wheels, Voice Control]                                                                           577
[Alloy wheels, Touch screen, Voice Control]                                                             541
                                                                                                       ... 
[Alloy wheels, Sport suspension, Touch screen, Trailer hitch, Voice Control]                              1
[Alloy wheels, Catalytic Converter, Handicapped enabled, Touch screen, Voice Control, Winter tyres]       1
[Ski bag, Sport suspension]                                                                               1
[Alloy wheels, Sport package

In [149]:
[",".join(item).strip() if type(item) == list else item for item in oto['\nExtras\n']]

['Alloy wheels,Catalytic Converter,Voice Control',
 'Alloy wheels,Sport seats,Sport suspension,Voice Control',
 'Alloy wheels,Voice Control',
 'Alloy wheels,Sport seats,Voice Control',
 'Alloy wheels,Sport package,Sport suspension,Voice Control',
 'Alloy wheels,Sport package,Sport seats,Sport suspension',
 'Alloy wheels,Sport package,Sport seats,Sport suspension',
 'Alloy wheels',
 'Alloy wheels',
 nan,
 'Alloy wheels,Shift paddles',
 'Alloy wheels,Sport seats',
 'Alloy wheels,Catalytic Converter,Sport package,Sport seats,Sport suspension,Voice Control',
 'Alloy wheels,Sport seats,Sport suspension',
 'Alloy wheels,Sport seats,Sport suspension',
 'Alloy wheels',
 'Alloy wheels,Sport package,Sport seats',
 'Alloy wheels,Sport package',
 'Alloy wheels',
 'Alloy wheels,Catalytic Converter,Shift paddles,Voice Control',
 'Alloy wheels,Shift paddles,Sport package,Voice Control',
 'Alloy wheels,Sport seats,Voice Control',
 'Alloy wheels,Catalytic Converter,Sport seats,Voice Control,Winter tyre

In [150]:
temp = pd.DataFrame([",".join(item).strip() if type(item) == list else item for item in oto['\nExtras\n']])

In [152]:
temp.isnull().sum()

0    2962
dtype: int64

In [157]:
oto["extra"] = pd.DataFrame([",".join(item).strip() if type(item) == list else item for item in oto['\nExtras\n']])

In [158]:
oto.extra.value_counts(dropna = False)

Alloy wheels                                                                                 3245
NaN                                                                                          2962
Alloy wheels,Touch screen                                                                     697
Alloy wheels,Voice Control                                                                    577
Alloy wheels,Touch screen,Voice Control                                                       541
                                                                                             ... 
Alloy wheels,Cab or rented Car,Catalytic Converter,Shift paddles,Sport seats,Touch screen       1
Alloy wheels,Catalytic Converter,Roof rack,Touch screen,Trailer hitch,Winter tyres              1
Roof rack,Sport seats,Winter tyres                                                              1
Alloy wheels,Cab or rented Car,Catalytic Converter,Roof rack,Sport seats                        1
Cab or rented Car,Sp

In [159]:
fill_most(oto, "make_model", "extra")

In [160]:
oto.extra.value_counts(dropna = False)

Alloy wheels                                                                                    6174
Alloy wheels,Touch screen                                                                        697
Alloy wheels,Voice Control                                                                       577
Alloy wheels,Touch screen,Voice Control                                                          541
Alloy wheels,Roof rack                                                                           385
                                                                                                ... 
Alloy wheels,Cab or rented Car,Catalytic Converter,Shift paddles,Sport seats,Touch screen          1
Alloy wheels,Catalytic Converter,Roof rack,Touch screen,Trailer hitch,Winter tyres                 1
Roof rack,Sport seats,Winter tyres                                                                 1
Alloy wheels,Cab or rented Car,Catalytic Converter,Roof rack,Sport seats                   

In [161]:
oto = oto.join(oto["extra"].str.get_dummies(sep = ",").add_prefix("ex_"))

In [162]:
oto.head()

url make_model                                   short_description body_type  price               vat         km registration      hp                                     Type Previous Owners                        Next Inspection                      Inspection new                          Warranty null      Make         Model     Offer Number First Registration       Body Color      Paint Type           Body Color Original          Upholstery Nr. of Doors Nr. of Seats      Model Code         Gearing Type    Displacement Cylinders  Drive chain                                   Fuel                                                               Consumption               CO2 Emission Emission Class                                                                                                                                                                                                                                                                                                     \nComfort & Convenience\n                                                                       \nEntertainment & Media\n                                                      \nExtras\n                                                                                                                                                                                                                                                                                 \nSafety & Security\n  \
0         https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e    Audi A1         Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770    VAT deductible  56,013 km      01/2016   66 kW  [, Used, , Diesel (Particulate Filter)]           \n2\n  [\n06/2021\n, \n99 g CO2/km (comb)\n]               [\nYes\n, \nEuro 6\n]           [\n, \n, \n4 (Green)\n]   []  \nAudi\n  [\n, A1, \n]  [\nLR-062483\n]     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]           [\nMythosschwarz\n]  [\nCloth, Black\n]      [\n5\n]      [\n5\n]  [\n0588/BDF\n]  [\n, Automatic, \n]  [\n1,422 cc\n]         3  [\nfront\n]  [\n, Diesel (Particulate Filter), \n]  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]   [\n99 g CO2/km (comb)\n]   [\nEuro 6\n]  [Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                     [Bluetooth, Hands-free equipment, On-board computer, Radio]              [Alloy wheels, Catalytic Converter, Voice Control]                                          [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]   
1                                      https://www.autoscout24.com//offers/audi-a1-1-8-tfsi-sport-gasoline-red-b2547f8a-e83f-6237-e053-e250040a56df    Audi A1                                      1.8 TFSI sport    Sedans  14500  Price negotiable  80,000 km      03/2017  141 kW                     [, Used, , Gasoline]             NaN                                    NaN                                 NaN                               NaN   []  \nAudi\n  [\n, A1, \n]              NaN     [\n, 2017, \n]    [\n, Red, \n]             NaN                           NaN   [\nCloth, Grey\n]      [\n3\n]      [\n4\n]  [\n0588/BCY\n]  [\n, Automatic, \n]  [\n1,798 cc\n]         4  [\nfront\n]                     [\n, Gasoline, \n]  [[5.6 l/100 km (comb)], [7.1 l/100 km (city)], [4.7 l/100 km (country)]]  [\n129 g CO2/km (comb)\n]   [\nEuro 6\n]                                                

In [163]:
oto.shape

(15919, 117)

***

### '\nSafety & Security\n'

In [164]:
oto['\nSafety & Security\n'].isnull().sum()/len(oto['\nSafety & Security\n'])*100

6.168729191532131

In [165]:
oto['\nSafety & Security\n'].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                                                                                                                                                                                                                                                                                                                                                                                        982
[ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control]                                                                                                                                                 538
[ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control]            

In [168]:
temp1 = [",".join(item).strip() if type(item) == list else item for item in oto['\nSafety & Security\n']]

In [169]:
oto["Safe&Secure"] = pd.DataFrame(temp1)

In [170]:
oto["Safe&Secure"].value_counts(dropna = False)

NaN                                                                                                                                                                                                                                                                                                                             982
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                    538
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                               480
ABS,Central door lock,Daytim

In [171]:
fill_most(oto, "make_model", "Safe&Secure")

In [172]:
oto["Safe&Secure"].value_counts(dropna = False)

ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                                                                                      825
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                                                                                                 480
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,LED Daytime Running Lights,Passen

In [173]:
oto = oto.join(oto["Safe&Secure"].str.get_dummies(sep = ",").add_prefix("ss_"))

In [174]:
oto.head()

url make_model                                   short_description body_type  price               vat         km registration      hp                                     Type Previous Owners                        Next Inspection                      Inspection new                          Warranty null      Make         Model     Offer Number First Registration       Body Color      Paint Type           Body Color Original          Upholstery Nr. of Doors Nr. of Seats      Model Code         Gearing Type    Displacement Cylinders  Drive chain                                   Fuel                                                               Consumption               CO2 Emission Emission Class                                                                                                                                                                                                                                                                                                     \nComfort & Convenience\n                                                                       \nEntertainment & Media\n                                                      \nExtras\n                                                                                                                                                                                                                                                                                 \nSafety & Security\n  \
0         https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e    Audi A1         Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770    VAT deductible  56,013 km      01/2016   66 kW  [, Used, , Diesel (Particulate Filter)]           \n2\n  [\n06/2021\n, \n99 g CO2/km (comb)\n]               [\nYes\n, \nEuro 6\n]           [\n, \n, \n4 (Green)\n]   []  \nAudi\n  [\n, A1, \n]  [\nLR-062483\n]     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]           [\nMythosschwarz\n]  [\nCloth, Black\n]      [\n5\n]      [\n5\n]  [\n0588/BDF\n]  [\n, Automatic, \n]  [\n1,422 cc\n]         3  [\nfront\n]  [\n, Diesel (Particulate Filter), \n]  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]   [\n99 g CO2/km (comb)\n]   [\nEuro 6\n]  [Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                     [Bluetooth, Hands-free equipment, On-board computer, Radio]              [Alloy wheels, Catalytic Converter, Voice Control]                                          [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]   
1                                      https://www.autoscout24.com//offers/audi-a1-1-8-tfsi-sport-gasoline-red-b2547f8a-e83f-6237-e053-e250040a56df    Audi A1                                      1.8 TFSI sport    Sedans  14500  Price negotiable  80,000 km      03/2017  141 kW                     [, Used, , Gasoline]             NaN                                    NaN                                 NaN                               NaN   []  \nAudi\n  [\n, A1, \n]              NaN     [\n, 2017, \n]    [\n, Red, \n]             NaN                           NaN   [\nCloth, Grey\n]      [\n3\n]      [\n4\n]  [\n0588/BCY\n]  [\n, Automatic, \n]  [\n1,798 cc\n]         4  [\nfront\n]                     [\n, Gasoline, \n]  [[5.6 l/100 km (comb)], [7.1 l/100 km (city)], [4.7 l/100 km (country)]]  [\n129 g CO2/km (comb)\n]   [\nEuro 6\n]                                                

In [175]:
oto.shape

(15919, 147)

***

### ``'Consumption'``

In [176]:
oto['Consumption'].isnull().sum()/len(oto['Consumption'])*100

11.973113889063383

In [182]:
oto['Consumption']

0                  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]
1                  [[5.6 l/100 km (comb)], [7.1 l/100 km (city)], [4.7 l/100 km (country)]]
2                  [[3.8 l/100 km (comb)], [4.4 l/100 km (city)], [3.4 l/100 km (country)]]
3                  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]
4                  [[4.1 l/100 km (comb)], [4.6 l/100 km (city)], [3.8 l/100 km (country)]]
                                                ...                                        
15914              [[5.3 l/100 km (comb)], [6.2 l/100 km (city)], [4.7 l/100 km (country)]]
15915    [\n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (city), \n, 6.3 l/100 km (country), \n]
15916              [[5.3 l/100 km (comb)], [6.2 l/100 km (city)], [4.7 l/100 km (country)]]
15917              [[5.3 l/100 km (comb)], [6.2 l/100 km (city)], [4.7 l/100 km (country)]]
15918              [[6.8 l/100 km (comb)], [8.7 l/100 km (city)], [5.7 l/100 km 

In [177]:
oto['Consumption'].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                                                                                   1906
[[3.9 l/100 km (comb)], [4.1 l/100 km (city)], [3.7 l/100 km (country)]]               304
[[4.2 l/100 km (comb)], [5 l/100 km (city)], [3.7 l/100 km (country)]]                 276
[[5.4 l/100 km (comb)], [6.8 l/100 km (city)], [4.5 l/100 km (country)]]               257
[[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]               253
                                                                                      ... 
[[3.6 l/100 km (comb)], [], [4.4 l/100 km (country)]]                                    1
[\n, 4.8 l/100 km (comb), \n, 5.6 l/100 km (city), \n, 4.3 l/100 km (country), \n]       1
[[7.6 l/100 km (comb)], [], []]                                                          1
[[5.6 l/100 km (comb)], [7.6 l/100 km (city)], [4.4 l/100 km (country)]]                 1
[\n, 4.7 l/100 km (comb), \n, \n, \n]                                                    1

In [178]:
oto['Consumption'].sample(55)

2523                 [[4.7 l/100 km (comb)], [5.9 l/100 km (city)], [4 l/100 km (country)]]
8788                                                                                    NaN
14490              [[5.7 l/100 km (comb)], [7.2 l/100 km (city)], [4.9 l/100 km (country)]]
7276               [[4.6 l/100 km (comb)], [5.5 l/100 km (city)], [4.1 l/100 km (country)]]
11027              [[3.9 l/100 km (comb)], [4.6 l/100 km (city)], [3.6 l/100 km (country)]]
11882              [[6.1 l/100 km (comb)], [7.5 l/100 km (city)], [5.3 l/100 km (country)]]
13394              [[3.5 l/100 km (comb)], [3.9 l/100 km (city)], [3.3 l/100 km (country)]]
1448               [[3.9 l/100 km (comb)], [4.5 l/100 km (city)], [3.6 l/100 km (country)]]
13351                                 [[], [3.3 l/100 km (city)], [3.5 l/100 km (country)]]
8382               [[5.6 l/100 km (comb)], [7.8 l/100 km (city)], [4.9 l/100 km (country)]]
7671                                                                            

In [179]:
oto['Consumption'].sample(55)

14121                [[5 l/100 km (comb)], [6.3 l/100 km (city)], [4.2 l/100 km (country)]]
11284                [[5.3 l/100 km (comb)], [7 l/100 km (city)], [4.3 l/100 km (country)]]
1482               [[3.9 l/100 km (comb)], [4.5 l/100 km (city)], [3.6 l/100 km (country)]]
11164                [[6.2 l/100 km (comb)], [8 l/100 km (city)], [5.2 l/100 km (country)]]
3184                                                                                    NaN
15794              [[5.3 l/100 km (comb)], [6.2 l/100 km (city)], [4.7 l/100 km (country)]]
4522               [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]
10403                                                                                   NaN
10039                [[5.6 l/100 km (comb)], [7 l/100 km (city)], [4.8 l/100 km (country)]]
14140              [[5.6 l/100 km (comb)], [7.2 l/100 km (city)], [4.7 l/100 km (country)]]
8295               [[5.2 l/100 km (comb)], [6.6 l/100 km (city)], [4.4 l/100 km 

In [180]:
oto['Consumption'].sample(55)

12201              [[6.2 l/100 km (comb)], [7.7 l/100 km (city)], [5.3 l/100 km (country)]]
13520              [[3.6 l/100 km (comb)], [4.3 l/100 km (city)], [3.2 l/100 km (country)]]
7413               [[4.7 l/100 km (comb)], [5.4 l/100 km (city)], [4.2 l/100 km (country)]]
1200                 [[4.3 l/100 km (comb)], [5 l/100 km (city)], [3.7 l/100 km (country)]]
9092               [[5.3 l/100 km (comb)], [6.6 l/100 km (city)], [4.5 l/100 km (country)]]
2095               [[4.8 l/100 km (comb)], [5.8 l/100 km (city)], [4.2 l/100 km (country)]]
10459              [[5.1 l/100 km (comb)], [6.5 l/100 km (city)], [4.2 l/100 km (country)]]
212                [[4.4 l/100 km (comb)], [5.4 l/100 km (city)], [3.8 l/100 km (country)]]
2568               [[4.6 l/100 km (comb)], [5.8 l/100 km (city)], [3.9 l/100 km (country)]]
1120               [[4.4 l/100 km (comb)], [5.4 l/100 km (city)], [3.8 l/100 km (country)]]
8663               [[5.3 l/100 km (comb)], [6.6 l/100 km (city)], [4.5 l/100 km 

#### There are three tpyes of value which can effect the result. 
 - Type 1-one list and three sub list (comb,city,country), like= ``[[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]``  
 - Type 2-one list and no sub list (comb,city,country), like = ``[\n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (city), \n, 6.3 l/100 km (country), \n]``  
 - Type 3-one list and three sub lists some of which are empty, like = ``[[], [4.6 l/100 km (city)], [5.7 l/100 km (country)]]`` or ``[[4.2 l/100 km (comb)], [], []]`` or `[[], [], [5.1 l/100 km (country)]]`
 - So, we use ``str.extract()`` to select numeric consumption(comb) in different ways below.

In [181]:
oto.Consumption.str[0]

0        [3.8 l/100 km (comb)]
1        [5.6 l/100 km (comb)]
2        [3.8 l/100 km (comb)]
3        [3.8 l/100 km (comb)]
4        [4.1 l/100 km (comb)]
                 ...          
15914    [5.3 l/100 km (comb)]
15915                       \n
15916    [5.3 l/100 km (comb)]
15917    [5.3 l/100 km (comb)]
15918    [6.8 l/100 km (comb)]
Name: Consumption, Length: 15919, dtype: object

In [183]:
oto.Consumption.str[0].value_counts(dropna = False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[6.7 l/100 km (comb)]      33
[3.9 l/100 km (comb)]     732
[4.4 l/100 km (comb)]     595
[5.4 l/100 km (comb)]     662
[5.1 kg/100 km (comb)]      3
[6.5 l/100 km (comb)]      36
[5.9 l/100 km (comb)]     308
[5.8 l/100 km (comb)]     142
[5.1 l/100 km (comb)]     627
[32 l/100 km (comb)]        1
[13.8 l/100 km (comb)]      1
[6.2 l/100 km (comb)]     184
[50 l/100 km (comb)]        1
[8.3 kg/100 km (comb)]      1
[3.6 kg/100 km (comb)]      1
[3.1 l/100 km (comb)]       7
[46 l/100 km (comb)]        1
[7.4 l/100 km (comb)]      62
[5.5 l/100 km (comb)]     342
[3 l/100 km (comb)]        69
[5.4 kg/100 km (comb)]      1
[3.8 l/100 km (comb)]     585
\n                        850
[1.2 l/100 km (comb)]       1
[7.2 l/100 km (comb)]       6
[7.9 l/100 km (comb)]       2
[38 l/100 km (comb)]        2
[4.5 l/100 km (comb)]     511
[7.3 l/100 km (comb)]       2
[7.1 l/100 km (comb)]      38
[5.3 l/100 km (comb)]     374
[8.3 l/100 km (comb)]      19
[4.1 l/100 km (comb)]     341
[55 l/100 

In [184]:
oto.Consumption.str[0].value_counts(dropna = False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[6.9 l/100 km (comb)]       21
[10 l/100 km (comb)]        34
[8.1 l/100 km (comb)]        2
[43 l/100 km (comb)]         1
[3.4 kg/100 km (comb)]      12
[7.8 l/100 km (comb)]        6
NaN                       1906
[6.6 l/100 km (comb)]      119
[3.4 l/100 km (comb)]       94
[7 l/100 km (comb)]          9
[6.8 l/100 km (comb)]      134
[8 l/100 km (comb)]          5
[7.1 l/100 km (comb)]       38
[13.8 l/100 km (comb)]       1
[3.9 l/100 km (comb)]      732
[3 l/100 km (comb)]         69
[8.7 l/100 km (comb)]        3
[5.7 l/100 km (comb)]      302
[5.4 l/100 km (comb)]      662
[3.7 l/100 km (comb)]      369
[3.8 l/100 km (comb)]      585
[4.7 l/100 km (comb)]      555
[7.6 l/100 km (comb)]       14
[5.6 l/100 km (comb)]      568
[4.6 l/100 km (comb)]      420
[7.9 l/100 km (comb)]        2
[3.3 kg/100 km (comb)]       9
[4.8 l/100 km (comb)]      523
[4.2 l/100 km (comb)]      408
[7.5 l/100 km (comb)]        1
[4 l/100 km (comb)]        712
[6.1 l/100 km (comb)]      135
[5.4 kg/

In [185]:
oto.Consumption.str[0].value_counts(dropna = False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[5.1 kg/100 km (comb)]       3
[4.6 l/100 km (comb)]      420
[6.7 l/100 km (comb)]       33
\n                         850
[3.7 l/100 km (comb)]      369
[4.3 l/100 km (comb)]      295
[6.4 l/100 km (comb)]       64
[6.3 l/100 km (comb)]      141
[3.3 l/100 km (comb)]      298
[4.4 l/100 km (comb)]      595
[3.4 l/100 km (comb)]       94
[6.1 l/100 km (comb)]      135
[5.9 l/100 km (comb)]      308
[3.4 kg/100 km (comb)]      12
[3.2 l/100 km (comb)]       25
[54 l/100 km (comb)]         1
[6.2 l/100 km (comb)]      184
[6.8 l/100 km (comb)]      134
[5.3 kg/100 km (comb)]       1
[3.5 l/100 km (comb)]      285
[5.5 l/100 km (comb)]      342
[3.6 kg/100 km (comb)]       1
[5.3 l/100 km (comb)]      374
[4.5 l/100 km (comb)]      511
[4.1 l/100 km (comb)]      341
[7.3 l/100 km (comb)]        2
[7.4 l/100 km (comb)]       62
[50 l/100 km (comb)]         1
[3.3 kg/100 km (comb)]       9
[]                         127
NaN                       1906
[3.6 l/100 km (comb)]      193
[8.3 kg/

- There are 850 values in which only 'one' list (the value of ``"\n"`` indicates that). Consists of no sub list. 

- There are 127 values is ``'[]'`` which means there is no ``comb`` consumption. Only have ``city`` or ``country`` or both.

- There are still 1906 ``NaN``s.

In [186]:
oto.Consumption.str[0].str[0].value_counts(dropna = False)

NaN                     2033
\n                       850
3.9 l/100 km (comb)      732
4 l/100 km (comb)        712
5.4 l/100 km (comb)      662
                        ... 
7.5 l/100 km (comb)        1
3.6 kg/100 km (comb)       1
1.2 l/100 km (comb)        1
43 l/100 km (comb)         1
46 l/100 km (comb)         1
Name: Consumption, Length: 81, dtype: int64

In [190]:
oto["Consumption"][12625][0][0]

'\n'

In [191]:
oto.Consumption.str[0].str[0].unique()

array(['3.8 l/100 km (comb)', '5.6 l/100 km (comb)',
       '4.1 l/100 km (comb)', '3.5 l/100 km (comb)',
       '3.7 l/100 km (comb)', nan, '4 l/100 km (comb)',
       '4.9 l/100 km (comb)', '4.2 l/100 km (comb)',
       '4.5 l/100 km (comb)', '4.4 l/100 km (comb)',
       '4.3 l/100 km (comb)', '3 l/100 km (comb)', '3.6 l/100 km (comb)',
       '3.4 l/100 km (comb)', '\n', '3.9 l/100 km (comb)',
       '5.1 l/100 km (comb)', '5.2 l/100 km (comb)',
       '4.6 l/100 km (comb)', '4.8 l/100 km (comb)',
       '5.8 l/100 km (comb)', '4.7 l/100 km (comb)', '5 l/100 km (comb)',
       '43 l/100 km (comb)', '13.8 l/100 km (comb)', '6 l/100 km (comb)',
       '5.9 l/100 km (comb)', '51 l/100 km (comb)', '5.3 l/100 km (comb)',
       '5.3 kg/100 km (comb)', '5.5 l/100 km (comb)',
       '3.4 kg/100 km (comb)', '10 l/100 km (comb)',
       '3.3 kg/100 km (comb)', '3.2 l/100 km (comb)',
       '3.5 kg/100 km (comb)', '6.6 l/100 km (comb)',
       '3.3 l/100 km (comb)', '8.3 l/100 km (comb)',
  

In [194]:
oto.Consumption.str[0].str[0].str.extract("(\d.\d|\d)")[0].unique()

array(['3.8', '5.6', '4.1', '3.5', '3.7', nan, '4', '4.9', '4.2', '4.5',
       '4.4', '4.3', '3', '3.6', '3.4', '3.9', '5.1', '5.2', '4.6', '4.8',
       '5.8', '4.7', '5', '1', '6', '5.9', '5.3', '5.5', '3.3', '3.2',
       '6.6', '8.3', '6.5', '7.1', '8.1', '5.4', '6.4', '6.7', '6.2',
       '7.3', '6.3', '5.7', '6.1', '6.8', '7.5', '7.4', '0', '7.8', '3.1',
       '6.9', '7', '7.2', '8', '9.1', '8.6', '8.7', '7.9', '1.2', '7.6'],
      dtype=object)

In [197]:
oto.Consumption.str[0].str[0].str.extract("(^\d*.\d*)").iloc[:,0].unique()

array(['3.8', '5.6', '4.1', '3.5', '3.7', nan, '4 ', '4.9', '4.2', '4.5',
       '4.4', '4.3', '3 ', '3.6', '3.4', '3.9', '5.1', '5.2', '4.6',
       '4.8', '5.8', '4.7', '5 ', '43 ', '13.8', '6 ', '5.9', '51 ',
       '5.3', '5.5', '10 ', '3.3', '3.2', '6.6', '8.3', '6.5', '7.1',
       '8.1', '5.4', '40 ', '38 ', '6.4', '6.7', '6.2', '7.3', '6.3',
       '5.7', '6.1', '6.8', '7.5', '7.4', '0 ', '7.8', '3.1', '6.9', '7 ',
       '7.2', '8 ', '11 ', '9.1', '8.6', '8.7', '7.9', '55 ', '54 ',
       '1.2', '32 ', '33 ', '50 ', '1 ', '46 ', '7.6'], dtype=object)

- If consumption is two digits, Extraction function takes only first one. 
   - eg.: ``40`` → ``4``
   - eg.: ``33`` → ``3``

In [198]:
oto.Consumption.str[0].str[0].str.extract("(\d.\d|\d)").isnull().sum()*100/oto.Consumption.str[0].str[0].str.extract('(\d.\d|\d)').shape[0]

0    18.110434
dtype: float64

In [199]:
oto["consumption_comb"] = oto.Consumption.str[0].str[0].str.extract("(\d.\d|\d)")

In [200]:
oto.consumption_comb.value_counts(dropna = False)

NaN    2883
3.9     732
4       716
5.4     663
5.1     630
4.4     595
3.8     585
5.6     568
4.7     555
4.8     523
5       520
4.5     511
5.2     429
4.6     420
4.2     408
5.3     375
3.7     369
4.9     348
5.5     342
4.1     341
5.9     308
3.3     307
5.7     302
4.3     295
3.5     288
6       278
3.6     194
6.2     184
5.8     142
6.3     141
6.1     135
6.8     134
6.6     119
3.4     106
3        73
6.4      64
7.4      62
7.1      38
1        37
6.5      36
6.7      33
3.2      25
6.9      21
8.3      20
7.6      14
7         9
3.1       7
7.8       6
7.2       6
8         5
8.6       3
8.7       3
7.3       2
7.9       2
8.1       2
0         2
1.2       1
7.5       1
9.1       1
Name: consumption_comb, dtype: int64

- Now, lets go into the other types. Let's try ``str[1]``

In [201]:
oto.Consumption.str[1].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                        1906
[5 l/100 km (city)]         642
[5.8 l/100 km (city)]       597
[4.5 l/100 km (city)]       577
[]                          516
                           ... 
[66 l/100 km (city)]          1
[10.5 kg/100 km (city)]       1
[64 l/100 km (city)]          1
7.9 l/100 km (comb)           1
8.6 l/100 km (comb)           1
Name: Consumption, Length: 130, dtype: int64

In [202]:
oto.Consumption.str[1].value_counts(dropna = False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[7.9 l/100 km (city)]        77
[7.1 l/100 km (city)]       221
5.5 l/100 km (comb)          38
[8.6 l/100 km (city)]        27
5.6 l/100 km (comb)          50
[6.8 kg/100 km (city)]        1
6.2 l/100 km (comb)          32
6.7 l/100 km (comb)          10
[6 l/100 km (city)]         239
[6.4 l/100 km (city)]       101
[7.8 l/100 km (city)]       341
6.8 l/100 km (comb)           2
[5 l/100 km (city)]         642
4.6 l/100 km (comb)           6
[10.8 l/100 km (city)]        3
NaN                        1906
[4.4 kg/100 km (city)]        1
[6.2 l/100 km (city)]       185
[19.9 l/100 km (city)]        1
8.6 l/100 km (comb)           1
[4.6 l/100 km (city)]       417
[7.7 l/100 km (city)]       165
[66 l/100 km (city)]          1
4.5 l/100 km (comb)          12
[4.4 l/100 km (city)]       135
[3.4 l/100 km (city)]        50
[6.7 l/100 km (city)]       286
[4 l/100 km (city)]         300
[10.5 kg/100 km (city)]       1
[4.2 l/100 km (city)]       353
[5.9 l/100 km (city)]       344
[3.8 l/1

In [203]:
oto.Consumption.str[1].value_counts(dropna = False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[5 l/100 km (city)]        642
[9.1 l/100 km (city)]       12
[8.7 l/100 km (city)]      158
[8.3 l/100 km (city)]       25
[6.8 kg/100 km (city)]       1
[4.3 kg/100 km (city)]      21
[5.9 l/100 km (city)]      344
[11 l/100 km (city)]         4
4.7 l/100 km (comb)         47
4.6 l/100 km (comb)          6
[4.4 l/100 km (city)]      135
[4 l/100 km (city)]        300
6.9 l/100 km (comb)          6
4.4 l/100 km (comb)         28
NaN                       1906
5.3 l/100 km (comb)          5
4.3 l/100 km (comb)         12
[3.8 l/100 km (city)]       25
5.8 l/100 km (comb)         22
[4.4 kg/100 km (city)]       1
[10.1 l/100 km (city)]       2
[6.7 l/100 km (city)]      286
7.4 l/100 km (comb)          4
6 l/100 km (comb)           53
[45 l/100 km (city)]         2
6.1 l/100 km (comb)         40
[5.8 l/100 km (city)]      597
[4.5 l/100 km (city)]      577
[8.1 l/100 km (city)]       21
[4.1 l/100 km (city)]      320
[16.1 l/100 km (city)]       1
[66 l/100 km (city)]         1
7 l/100 

In [204]:
consumption1 = oto.Consumption.str[1].str.extract("(\d.\d|\d)")

In [205]:
consumption1.head()

0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN

In [206]:
consumption1[0].value_counts(dropna = False)

NaN    15069
5.4      107
5.9       61
6         53
5.6       50
4.7       47
4.9       45
6.1       40
5.7       40
6.3       40
5.5       38
5         32
6.2       32
6.6       29
4.4       28
5.1       27
4.2       27
5.2       25
4.8       23
5.8       22
4.5       12
4.3       12
6.4       11
6.7       10
6.5        7
6.9        6
4.6        6
5.3        5
7.4        4
1.6        3
6.8        2
7          1
8.6        1
7.9        1
4.1        1
4          1
3.9        1
Name: 0, dtype: int64

In [208]:
consumption1[0].value_counts().sum()

850

In [210]:
oto["consumption_comb"].value_counts(dropna = False)

NaN    2883
3.9     732
4       716
5.4     663
5.1     630
4.4     595
3.8     585
5.6     568
4.7     555
4.8     523
5       520
4.5     511
5.2     429
4.6     420
4.2     408
5.3     375
3.7     369
4.9     348
5.5     342
4.1     341
5.9     308
3.3     307
5.7     302
4.3     295
3.5     288
6       278
3.6     194
6.2     184
5.8     142
6.3     141
6.1     135
6.8     134
6.6     119
3.4     106
3        73
6.4      64
7.4      62
7.1      38
1        37
6.5      36
6.7      33
3.2      25
6.9      21
8.3      20
7.6      14
7         9
3.1       7
7.8       6
7.2       6
8         5
8.6       3
8.7       3
7.3       2
7.9       2
8.1       2
0         2
1.2       1
7.5       1
9.1       1
Name: consumption_comb, dtype: int64

In [212]:
oto.consumption_comb.fillna(consumption1[0]).value_counts(dropna = False)

NaN    2033
5.4     770
3.9     733
4       717
5.1     657
4.4     623
5.6     618
4.7     602
3.8     585
5       552
4.8     546
4.5     523
5.2     454
4.2     435
4.6     426
4.9     393
5.5     380
5.3     380
5.9     369
3.7     369
4.1     342
5.7     342
6       331
4.3     307
3.3     307
3.5     288
6.2     216
3.6     194
6.3     181
6.1     175
5.8     164
6.6     148
6.8     136
3.4     106
6.4      75
3        73
7.4      66
6.7      43
6.5      43
7.1      38
1        37
6.9      27
3.2      25
8.3      20
7.6      14
7        10
3.1       7
7.2       6
7.8       6
8         5
8.6       4
7.9       3
8.7       3
1.6       3
8.1       2
7.3       2
0         2
7.5       1
1.2       1
9.1       1
Name: consumption_comb, dtype: int64

In [213]:
oto.consumption_comb.fillna(consumption1[0], inplace = True)

In [214]:
oto.consumption_comb.value_counts(dropna = False)

NaN    2033
5.4     770
3.9     733
4       717
5.1     657
4.4     623
5.6     618
4.7     602
3.8     585
5       552
4.8     546
4.5     523
5.2     454
4.2     435
4.6     426
4.9     393
5.5     380
5.3     380
5.9     369
3.7     369
4.1     342
5.7     342
6       331
4.3     307
3.3     307
3.5     288
6.2     216
3.6     194
6.3     181
6.1     175
5.8     164
6.6     148
6.8     136
3.4     106
6.4      75
3        73
7.4      66
6.7      43
6.5      43
7.1      38
1        37
6.9      27
3.2      25
8.3      20
7.6      14
7        10
3.1       7
7.2       6
7.8       6
8         5
8.6       4
7.9       3
8.7       3
1.6       3
8.1       2
7.3       2
0         2
7.5       1
1.2       1
9.1       1
Name: consumption_comb, dtype: int64

In [215]:
oto.consumption_comb.isnull().sum()*100/oto.consumption_comb.shape[0]

12.770902694892895

In [216]:
oto["Consumption"].str[-2].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                        1906
[5 l/100 km (city)]         642
[5.8 l/100 km (city)]       597
[4.5 l/100 km (city)]       577
[]                          516
                           ... 
[10.4 l/100 km (city)]        1
[19.9 l/100 km (city)]        1
[9 l/100 km (city)]           1
[10.5 kg/100 km (city)]       1
[66 l/100 km (city)]          1
Name: Consumption, Length: 121, dtype: int64

In [218]:
oto["Consumption"].str[1].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                        1906
[5 l/100 km (city)]         642
[5.8 l/100 km (city)]       597
[4.5 l/100 km (city)]       577
[]                          516
                           ... 
[66 l/100 km (city)]          1
[10.5 kg/100 km (city)]       1
[64 l/100 km (city)]          1
7.9 l/100 km (comb)           1
8.6 l/100 km (comb)           1
Name: Consumption, Length: 130, dtype: int64

In [219]:
oto["Consumption"].str[-2].str[0].value_counts(dropna = False)

NaN                      2422
5 l/100 km (city)         642
5.8 l/100 km (city)       597
4.5 l/100 km (city)       577
4                         532
                         ... 
64 l/100 km (city)          1
9.7 l/100 km (city)         1
10.5 kg/100 km (city)       1
10.4 l/100 km (city)        1
16.1 l/100 km (city)        1
Name: Consumption, Length: 99, dtype: int64

In [220]:
oto["Consumption"].str[-2].str[0].unique()

array(['4.3 l/100 km (city)', '7.1 l/100 km (city)',
       '4.4 l/100 km (city)', '4.6 l/100 km (city)',
       '4.2 l/100 km (city)', nan, '6.2 l/100 km (city)',
       '5 l/100 km (city)', '5.5 l/100 km (city)', '5.4 l/100 km (city)',
       '3.8 l/100 km (city)', '5.2 l/100 km (city)', '3 l/100 km (city)',
       '4 l/100 km (city)', '3.9 l/100 km (city)', '4.1 l/100 km (city)',
       '3', '4.7 l/100 km (city)', '6.3 l/100 km (city)',
       '6.7 l/100 km (city)', '5.6 l/100 km (city)',
       '4.8 l/100 km (city)', '6.6 l/100 km (city)',
       '4.5 l/100 km (city)', '5.8 l/100 km (city)', '4',
       '7.4 l/100 km (city)', '6.1 l/100 km (city)',
       '3.7 l/100 km (city)', '5.1 l/100 km (city)',
       '19.9 l/100 km (city)', '6.4 l/100 km (city)',
       '8.2 l/100 km (city)', '6 l/100 km (city)', '6.5 l/100 km (city)',
       '5.9 l/100 km (city)', '8 l/100 km (city)', '62 l/100 km (city)',
       '6.8 l/100 km (city)', '7.5 l/100 km (city)',
       '3.5 l/100 km (city)', '5

In [223]:
oto["Consumption"].str[-2].str[0].str.extract("(\d.\d|\d)")[0].value_counts(dropna = False)

NaN    2436
5       858
4       836
5.8     600
4.5     580
       ... 
8.8       2
3.6       2
9.5       2
9         1
9.7       1
Name: 0, Length: 70, dtype: int64

In [224]:
consumption_city = oto["Consumption"].str[-2].str[0].str.extract("(\d.\d|\d)")

In [226]:
consumption_city = pd.to_numeric(consumption_city[0])

In [227]:
consumption_city

0        4.3
1        7.1
2        4.4
3        4.3
4        4.6
        ... 
15914    6.2
15915    6.0
15916    6.2
15917    6.2
15918    8.7
Name: 0, Length: 15919, dtype: float64

- Let's take a look at the "``country``"

In [221]:
oto["Consumption"].str[-1].str[0].unique()

array(['3.5 l/100 km (country)', '4.7 l/100 km (country)',
       '3.4 l/100 km (country)', '3.8 l/100 km (country)',
       '3.1 l/100 km (country)', nan, '3.6 l/100 km (country)',
       '4.2 l/100 km (country)', '3.7 l/100 km (country)',
       '3.9 l/100 km (country)', '3.3 l/100 km (country)',
       '3 l/100 km (country)', '\n', '4.4 l/100 km (country)',
       '4 l/100 km (country)', '4.3 l/100 km (country)',
       '4.9 l/100 km (country)', '4.1 l/100 km (country)',
       '4.5 l/100 km (country)', '3.2 l/100 km (country)',
       '10.3 l/100 km (country)', '5.1 l/100 km (country)',
       '6.7 l/100 km (country)', '6.3 l/100 km (country)',
       '4.8 l/100 km (country)', '44 l/100 km (country)',
       '5.4 l/100 km (country)', '4.6 l/100 km (country)',
       '4.6 kg/100 km (country)', '2.9 kg/100 km (country)',
       '2.8 kg/100 km (country)', '5.6 l/100 km (country)',
       '6.6 l/100 km (country)', '6 l/100 km (country)',
       '6.5 l/100 km (country)', '4.5 kg/100 km 

In [228]:
oto['Consumption'].str[-1].str[0].value_counts(dropna = False)

NaN                        2362
4.2 l/100 km (country)     1101
3.7 l/100 km (country)     1059
\n                          850
4.4 l/100 km (country)      829
                           ... 
4.5 kg/100 km (country)       1
42 l/100 km (country)         1
3 kg/100 km (country)         1
10.3 l/100 km (country)       1
8 l/100 km (country)          1
Name: Consumption, Length: 65, dtype: int64

In [229]:
oto['Consumption'].str[-1].str[0].str.extract('(\d.\d|\d)')[0].value_counts(dropna = False)

NaN    3212
4.2    1101
3.7    1059
4.4     829
4.5     789
3.8     775
3.9     759
4.1     569
4.7     562
4       560
3.5     525
4.3     496
3.6     486
3.1     481
3.3     456
4.6     446
4.9     410
3.4     353
4.8     289
5.3     227
5.1     215
5.7     191
5.4     190
3.2     180
3       146
5.6     131
5       106
5.2      84
6.3      49
6        35
1        34
5.5      30
5.8      30
7.7      20
6.6      19
2.9      16
6.4      15
0         9
2.8       9
7.3       4
6.5       4
7.1       3
7         2
6.7       2
7.8       2
6.9       2
5.9       2
8.6       1
6.1       1
8         1
2         1
7.6       1
Name: 0, dtype: int64

In [230]:
consumption_country = oto['Consumption'].str[-1].str[0].str.extract('(\d.\d|\d)')

In [231]:
consumption_country = pd.to_numeric(consumption_country[0])

In [232]:
consumption_country

0        3.5
1        4.7
2        3.4
3        3.5
4        3.8
        ... 
15914    4.7
15915    NaN
15916    4.7
15917    4.7
15918    5.7
Name: 0, Length: 15919, dtype: float64

In [233]:
consumption_city

0        4.3
1        7.1
2        4.4
3        4.3
4        4.6
        ... 
15914    6.2
15915    6.0
15916    6.2
15917    6.2
15918    8.7
Name: 0, Length: 15919, dtype: float64

In [234]:
(consumption_city + consumption_country) / 2

0        3.90
1        5.90
2        3.90
3        3.90
4        4.20
         ... 
15914    5.45
15915     NaN
15916    5.45
15917    5.45
15918    7.20
Name: 0, Length: 15919, dtype: float64

In [235]:
consumption2 = (consumption_city + consumption_country) / 2

In [236]:
consumption2.value_counts(dropna = False)

NaN     3283
3.90     610
5.65     498
4.75     497
4.10     439
        ... 
7.70       1
7.25       1
7.45       1
7.20       1
7.35       1
Name: 0, Length: 139, dtype: int64

In [237]:
oto.consumption_comb.fillna(consumption2).value_counts(dropna = False)

NaN     1925
5.4      770
3.9      733
4        717
5.1      657
        ... 
7.5        1
9.1        1
4.5        1
4.55       1
5.8        1
Name: consumption_comb, Length: 70, dtype: int64

In [238]:
oto.consumption_comb.fillna(consumption2, inplace = True)

In [239]:
oto.consumption_comb.value_counts(dropna = False)

NaN     1925
5.4      770
3.9      733
4        717
5.1      657
        ... 
7.5        1
9.1        1
4.5        1
4.55       1
5.8        1
Name: consumption_comb, Length: 70, dtype: int64

***

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

# Exploratory Data Analysis Project (Part - 1) - Session - 5

<blockquote style="background: #f9f9f9;padding: 0.5em 10px;" class="">
<img src="https://docs.google.com/uc?id=1FOcuE9AkAqc0JU6dUly-cuoUg3bOp92H" class="img-fluid" width="200" height="85"> <h1>EDA for Car Price Prediction Model</h1>
</blockquote>

### ``'Gearing Type'``

In [240]:
oto["Gearing Type"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n, Manual, \n]            8153
[\n, Automatic, \n]         7297
[\n, Semi-automatic, \n]     469
Name: Gearing Type, dtype: int64

In [241]:
oto['Gearing Type'].str[1].value_counts()

Manual            8153
Automatic         7297
Semi-automatic     469
Name: Gearing Type, dtype: int64

In [242]:
oto["gear_type"] = oto['Gearing Type'].str[1]

In [243]:
oto.gear_type.head()

0    Automatic
1    Automatic
2    Automatic
3    Automatic
4    Automatic
Name: gear_type, dtype: object

***

### ``'Drive chain'``

In [244]:
oto["Drive chain"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\nfront\n]    8886
NaN            6858
[\n4WD\n]       171
[\nrear\n]        4
Name: Drive chain, dtype: int64

- We can handle with missig values or we can drop it. Let's take a look at this issue later.

In [245]:
oto["drive_chain"] = oto["Drive chain"].str[0].str.strip("\n")

In [246]:
oto.drive_chain.value_counts(dropna = False)

front    8886
NaN      6858
4WD       171
rear        4
Name: drive_chain, dtype: int64

***

### ``'Model Code'``

In [247]:
oto["Model Code"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN               10941
[\n0035/BCB\n]      268
[\n0588/BNO\n]      245
[\n0588/BDB\n]      206
[\n0588/BHX\n]      188
                  ...  
[\n1844/AEN\n]        1
[\n0588/AVR\n]        1
[\n0035/AFF\n]        1
[\n1844/AFM\n]        1
[\n0035/AVN\n]        1
Name: Model Code, Length: 233, dtype: int64

In [248]:
oto["Model Code"].str[0].str.strip("\n")

0        0588/BDF
1        0588/BCY
2             NaN
3             NaN
4        0588/BDF
           ...   
15914         NaN
15915    0000/000
15916         NaN
15917         NaN
15918    3333/BHJ
Name: Model Code, Length: 15919, dtype: object

In [249]:
oto.drop("Model Code", axis = 1, inplace = True)

***

## Now we start to analyze the variables which has below %35 percentage of missing values.

### ``'Body Color'``

In [250]:
oto["Body Color"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n, Black, \n]     3745
[\n, Grey, \n]      3505
[\n, White, \n]     3406
[\n, Silver, \n]    1647
[\n, Blue, \n]      1431
[\n, Red, \n]        957
NaN                  597
[\n, Brown, \n]      289
[\n, Green, \n]      154
[\n, Beige, \n]      108
[\n, Yellow, \n]      51
[\n, Violet, \n]      18
[\n, Bronze, \n]       6
[\n, Orange, \n]       3
[\n, Gold, \n]         2
Name: Body Color, dtype: int64

In [251]:
oto["Body Color"].str[1].value_counts(dropna = False)

Black     3745
Grey      3505
White     3406
Silver    1647
Blue      1431
Red        957
NaN        597
Brown      289
Green      154
Beige      108
Yellow      51
Violet      18
Bronze       6
Orange       3
Gold         2
Name: Body Color, dtype: int64

In [254]:
oto['Body_Color'] = oto['Body Color'].str[1].str.strip()
oto.Body_Color 

0        Black
1          Red
2        Black
3        Brown
4        Black
         ...  
15914     Grey
15915     Grey
15916    White
15917     Grey
15918     Grey
Name: Body_Color, Length: 15919, dtype: object

In [255]:
oto.Body_Color.fillna(method = "bfill", inplace = True)

In [256]:
oto.Body_Color.value_counts(dropna = False)

Black     3888
Grey      3638
White     3540
Silver    1687
Blue      1524
Red        989
Brown      299
Green      163
Beige      108
Yellow      53
Violet      18
Bronze       7
Orange       3
Gold         2
Name: Body_Color, dtype: int64

***

### ``'Body Color Original'``

In [257]:
oto["Body Color Original"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                             3759
[\nOnyx Schwarz\n]               338
[\nBianco\n]                     282
[\nMythosschwarz Metallic\n]     238
[\nBrillantschwarz\n]            216
                                ... 
[\nBianca - Tetto Nero\n]          1
[\ndezir rot\n]                    1
[\nnero/tetto argento met\n]       1
[\nPython Yellow Metallic\n]       1
[\nkarbongrau\n]                   1
Name: Body Color Original, Length: 1928, dtype: int64

In [258]:
oto.drop("Body Color Original", axis = 1, inplace = True)

***

### ``'CO2 Emission'``

In [259]:
oto["CO2 Emission"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                            1808
[\n120 g CO2/km (comb)\n]       740
[[], [], []]                    628
[\n99 g CO2/km (comb)\n]        545
[\n97 g CO2/km (comb)\n]        537
                               ... 
[\n193 g CO2/km (comb)\n]         1
[\n171 g CO2/km (comb)\n]         1
[\n990 g CO2/km (comb)\n]         1
[\n1,060 g CO2/km (comb)\n]       1
[\n183 g CO2/km (comb)\n]         1
Name: CO2 Emission, Length: 124, dtype: int64

In [260]:
oto["CO2 Emission"].str[0].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                        1808
\n120 g CO2/km (comb)\n     740
[]                          628
\n99 g CO2/km (comb)\n      545
\n97 g CO2/km (comb)\n      537
                           ... 
\n193 g CO2/km (comb)\n       1
\n171 g CO2/km (comb)\n       1
\n1 g CO2/km (comb)\n         1
\n181 g CO2/km (comb)\n       1
\n14 g CO2/km (comb)\n        1
Name: CO2 Emission, Length: 124, dtype: int64

In [261]:
oto['CO2 Emission'].str[0].str.strip('\n').value_counts(dropna = False).sample(55)

110 g CO2/km (comb)        266
136 g CO2/km (comb)        145
331 g CO2/km (comb)          1
96 g CO2/km (comb)          22
119 g CO2/km (comb)        361
189 g CO2/km (comb)         19
0 g CO2/km (comb)            2
146 g CO2/km (comb)         36
134 g CO2/km (comb)        130
187 g CO2/km (comb)         26
181 g CO2/km (comb)          1
142 g CO2/km (comb)         58
145 g CO2/km (comb)        126
167 g CO2/km (comb)          2
197 g CO2/km (comb)          4
147 g CO2/km (comb)        109
157 g CO2/km (comb)         18
155 g CO2/km (comb)          8
104 g CO2/km (comb)        501
106 g CO2/km (comb)        349
990 g CO2/km (comb)          1
90 g CO2/km (comb)          35
152 g CO2/km (comb)         28
NaN                       2436
51 g CO2/km (comb)           1
87 g CO2/km (comb)           6
105 g CO2/km (comb)        202
98 g CO2/km (comb)         151
151 g CO2/km (comb)         34
127 g CO2/km (comb)        257
153 g CO2/km (comb)        113
118 g CO2/km (comb)        270
1,060 g 

In [262]:
oto['CO2 Emission'].str[0].str.strip('\n').value_counts(dropna = False).sample(55)

193 g CO2/km (comb)         1
183 g CO2/km (comb)         1
147 g CO2/km (comb)       109
155 g CO2/km (comb)         8
107 g CO2/km (comb)       362
106 g CO2/km (comb)       349
120 g CO2/km (comb)       740
160 g CO2/km (comb)         1
119 g CO2/km (comb)       361
168 g CO2/km (comb)        58
117 g CO2/km (comb)       254
36 g CO2/km (comb)          3
157 g CO2/km (comb)        18
177 g CO2/km (comb)         1
109 g CO2/km (comb)       234
135 g CO2/km (comb)       202
161 g CO2/km (comb)        10
14 g CO2/km (comb)          1
188 g CO2/km (comb)         7
184 g CO2/km (comb)         1
187 g CO2/km (comb)        26
115 g CO2/km (comb)        86
150 g CO2/km (comb)       174
127 g CO2/km (comb)       257
146 g CO2/km (comb)        36
154 g CO2/km (comb)        40
114 g CO2/km (comb)       382
162 g CO2/km (comb)         2
125 g CO2/km (comb)       132
1,060 g CO2/km (comb)       1
124 g CO2/km (comb)       372
153 g CO2/km (comb)       113
137 g CO2/km (comb)       133
165 g CO2/

In [263]:
oto["CO2 Emission"].str[0].str.strip("\n").str.replace(",", "").value_counts(dropna = False).sample(55)

109 g CO2/km (comb)      234
111 g CO2/km (comb)      237
151 g CO2/km (comb)       34
199 g CO2/km (comb)        2
122 g CO2/km (comb)       83
127 g CO2/km (comb)      257
150 g CO2/km (comb)      174
88 g CO2/km (comb)        15
126 g CO2/km (comb)      282
148 g CO2/km (comb)       48
145 g CO2/km (comb)      126
51 g CO2/km (comb)         1
153 g CO2/km (comb)      113
131 g CO2/km (comb)       48
102 g CO2/km (comb)      477
121 g CO2/km (comb)       82
147 g CO2/km (comb)      109
98 g CO2/km (comb)       151
96 g CO2/km (comb)        22
120 g CO2/km (comb)      740
170 g CO2/km (comb)       10
166 g CO2/km (comb)        8
13983 g CO2/km (comb)      1
132 g CO2/km (comb)      100
141 g CO2/km (comb)      156
80 g CO2/km (comb)         1
177 g CO2/km (comb)        1
89 g CO2/km (comb)        19
146 g CO2/km (comb)       36
128 g CO2/km (comb)      329
85 g CO2/km (comb)       275
125 g CO2/km (comb)      132
99 g CO2/km (comb)       545
45 g CO2/km (comb)         1
12324 g CO2/km

In [264]:
oto['CO2 Emission'].str[0].str.strip('\n').str.replace(",", "").unique()

array(['99 g CO2/km (comb)', '129 g CO2/km (comb)', '109 g CO2/km (comb)',
       '92 g CO2/km (comb)', '98 g CO2/km (comb)', '97 g CO2/km (comb)',
       nan, '105 g CO2/km (comb)', '112 g CO2/km (comb)',
       '103 g CO2/km (comb)', '102 g CO2/km (comb)', '95 g CO2/km (comb)',
       '104 g CO2/km (comb)', '91 g CO2/km (comb)', '94 g CO2/km (comb)',
       '117 g CO2/km (comb)', '123 g CO2/km (comb)',
       '106 g CO2/km (comb)', '108 g CO2/km (comb)',
       '121 g CO2/km (comb)', '107 g CO2/km (comb)',
       '101 g CO2/km (comb)', '113 g CO2/km (comb)',
       '137 g CO2/km (comb)', '100 g CO2/km (comb)',
       '116 g CO2/km (comb)', '114 g CO2/km (comb)',
       '118 g CO2/km (comb)', '331 g CO2/km (comb)',
       '115 g CO2/km (comb)', '119 g CO2/km (comb)', '90 g CO2/km (comb)',
       '136 g CO2/km (comb)', '134 g CO2/km (comb)',
       '110 g CO2/km (comb)', '111 g CO2/km (comb)',
       '120 g CO2/km (comb)', '89 g CO2/km (comb)', '142 g CO2/km (comb)',
       '126 g CO2/

In [265]:
pattern = "(\d\d\d\d\d|\d\d\d\d|\d\d\d|\d\d|\d)"

In [266]:
oto["CO2_Emission"] = oto['CO2 Emission'].str[0].str.strip('\n').str.replace(",", "").str.extract(pattern)

In [267]:
oto["CO2_Emission"].value_counts(dropna = False)

NaN    2436
120     740
99      545
97      537
104     501
       ... 
51        1
14        1
180       1
45        1
253       1
Name: CO2_Emission, Length: 123, dtype: int64

In [268]:
oto["CO2_Emission"].unique()

array(['99', '129', '109', '92', '98', '97', nan, '105', '112', '103',
       '102', '95', '104', '91', '94', '117', '123', '106', '108', '121',
       '107', '101', '113', '137', '100', '116', '114', '118', '331',
       '115', '119', '90', '136', '134', '110', '111', '120', '89', '142',
       '126', '122', '128', '127', '138', '130', '125', '85', '124',
       '152', '88', '189', '194', '149', '153', '188', '36', '1060', '96',
       '990', '146', '135', '158', '12087', '141', '172', '154', '150',
       '167', '174', '93', '133', '131', '145', '147', '156', '87', '5',
       '148', '139', '151', '144', '168', '160', '170', '80', '132',
       '155', '14', '159', '0', '143', '140', '82', '12324', '84', '165',
       '51', '157', '169', '166', '253', '164', '175', '190', '161',
       '239', '197', '184', '14457', '199', '13983', '187', '181', '186',
       '177', '180', '162', '45', '171', '183', '1', '191', '193'],
      dtype=object)

- let's fill missing values using median.

In [269]:
oto.CO2_Emission.median()

116.0

In [270]:
oto.CO2_Emission.fillna(oto.CO2_Emission.median(), inplace = True)

In [271]:
oto['CO2_Emission'].value_counts(dropna=False)

116.0    2436
120       740
99        545
97        537
104       501
         ... 
177         1
253         1
12324       1
45          1
183         1
Name: CO2_Emission, Length: 123, dtype: int64

***

### ``'Displacement'``

In [272]:
oto.Displacement.isnull().sum()/oto.Displacement.shape[0]*100

3.11577360386959

In [273]:
oto.Displacement.value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n1,598 cc\n]     4761
[\n999 cc\n]       2438
[\n1,398 cc\n]     1314
[\n1,399 cc\n]      749
[\n1,229 cc\n]      677
                   ... 
[\n1,800 cc\n]        1
[\n140 cc\n]          1
[\n15,898 cc\n]       1
[\n1,686 cc\n]        1
[\n1,368 cc\n]        1
Name: Displacement, Length: 78, dtype: int64

In [274]:
oto.Displacement.str[0].str.strip('\n')

0        1,422 cc
1        1,798 cc
2        1,598 cc
3        1,422 cc
4        1,422 cc
           ...   
15914    1,997 cc
15915    1,798 cc
15916    1,997 cc
15917    1,997 cc
15918    1,798 cc
Name: Displacement, Length: 15919, dtype: object

In [275]:
oto['Displacement_cc'] = oto.Displacement.str[0].str.strip('\n')
oto.Displacement_cc

0        1,422 cc
1        1,798 cc
2        1,598 cc
3        1,422 cc
4        1,422 cc
           ...   
15914    1,997 cc
15915    1,798 cc
15916    1,997 cc
15917    1,997 cc
15918    1,798 cc
Name: Displacement_cc, Length: 15919, dtype: object

In [ ]:
#oto.replace({"Displacement_cc" : {}, "ikinci sutun" : {}, "üçüncü" : {}})

In [276]:
oto.replace({"Displacement_cc" : {"," : "", " " : "", "cc" : ""}}, regex = True, inplace = True)

In [277]:
oto.Displacement_cc.value_counts(dropna = False).head(44)

1598    4761
999     2438
1398    1314
1399     749
1229     677
1956     670
1461     595
1490     559
NaN      496
1422     467
1197     353
898      351
1395     320
1968     301
1149     288
1618     212
1798     210
1498     196
1600     130
1248     110
1997     103
1364     102
1400      90
998       72
1500      50
2000      46
1000      40
1         36
1998      25
2480      20
1200      18
1984      18
1397      11
899       11
160        6
929        5
1499       5
1596       4
139        4
997        4
900        4
1396       3
1199       3
1599       3
Name: Displacement_cc, dtype: int64

In [278]:
oto.Displacement_cc = pd.to_numeric(oto.Displacement_cc)

oto.Displacement_cc

0        1422.0
1        1798.0
2        1598.0
3        1422.0
4        1422.0
          ...  
15914    1997.0
15915    1798.0
15916    1997.0
15917    1997.0
15918    1798.0
Name: Displacement_cc, Length: 15919, dtype: float64

***

### ``'Emission Class'``

In [279]:
oto['Emission Class'].isnull().sum()/oto['Emission Class'].shape[0]*100

18.97732269614926

In [280]:
oto['Emission Class'].str[0].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


\nEuro 6\n          10139
NaN                  3021
\nEuro 6d-TEMP\n     1845
[]                    607
\nEuro 6c\n           127
\nEuro 5\n             78
\nEuro 6d\n            62
\nEuro 4\n             40
Name: Emission Class, dtype: int64

In [281]:
oto['Emission Class'].str[0].str.strip('\n').value_counts(dropna=False)

Euro 6          10139
NaN              3628
Euro 6d-TEMP     1845
Euro 6c           127
Euro 5             78
Euro 6d            62
Euro 4             40
Name: Emission Class, dtype: int64

In [282]:
oto['Emission_Class'] = oto['Emission Class'].str[0].str.strip('\n')

In [283]:
oto.replace({"Emission_Class" : {"Euro 6d-TEMP":"Euro 6", "Euro 6c":"Euro 6", "Euro 6d":"Euro 6"}}, regex = True, inplace = True)

In [284]:
oto.Emission_Class.value_counts(dropna=False)

Euro 6    12173
NaN        3628
Euro 5       78
Euro 4       40
Name: Emission_Class, dtype: int64

***

### ``'First Registration'``

In [285]:
oto['First Registration'].isnull().sum()/oto['First Registration'].shape[0]*100

10.032037188265594

In [286]:
oto['First Registration'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n, 2018, \n]    4522
[\n, 2016, \n]    3674
[\n, 2017, \n]    3273
[\n, 2019, \n]    2853
NaN               1597
Name: First Registration, dtype: int64

In [287]:
oto['register_age'] = pd.to_numeric(oto['First Registration'].str[1]) 

oto.register_age.value_counts(dropna=False)

2018.0    4522
2016.0    3674
2017.0    3273
2019.0    2853
NaN       1597
Name: register_age, dtype: int64

In [288]:
oto.register_age = 2020 - oto.register_age

- We can transform this feature into an "age" column. Let's create a new column called ``"register_age"``

In [289]:
oto.register_age.value_counts(dropna = False)

2.0    4522
4.0    3674
3.0    3273
1.0    2853
NaN    1597
Name: register_age, dtype: int64

***

### ``'Fuel'``

In [292]:
oto.Fuel.isnull().sum()/oto.Fuel.shape[0]*100

0.0

In [293]:
oto.Fuel.value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n, Diesel (Particulate Filter), \n]                                                                                  4315
[\n, Super 95, \n]                                                                                                     3338
[\n, Gasoline, \n]                                                                                                     3175
[\n, Diesel, \n]                                                                                                       2984
[\n, Super 95 / Regular/Benzine 91, \n]                                                                                 424
                                                                                                                       ... 
[\n, Super Plus 98 / Super E10 95, \n]                                                                                    1
[\n, Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91 / Super E10 95 / Super Plus 98 / Super Plus E10 98, \n]       1
[\n, Sup

In [294]:
oto.Fuel.value_counts(dropna=False).head(40)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n, Diesel (Particulate Filter), \n]                                                                                  4315
[\n, Super 95, \n]                                                                                                     3338
[\n, Gasoline, \n]                                                                                                     3175
[\n, Diesel, \n]                                                                                                       2984
[\n, Super 95 / Regular/Benzine 91, \n]                                                                                 424
[\n, Regular/Benzine 91, \n]                                                                                            354
[\n, Super E10 95, \n]                                                                                                  331
[\n, Super 95 (Particulate Filter), \n]                                                                                 268
[\n, Sup

In [295]:
oto.Fuel.value_counts(dropna=False).tail(40)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n, Super 95 / Regular/Benzine 91 / Super Plus 98, \n]                                                                                     2
[\n, Super E10 95 / Regular/Benzine 91, \n]                                                                                                 2
[\n, Regular/Benzine 91 / Super 95 / Super Plus 98 / Super Plus E10 98 / Super E10 95 / Regular/Benzine E10 91, \n]                         2
[\n, Super Plus 98 / Super 95 / Super Plus E10 98, \n]                                                                                      1
[\n, Super 95 / Super E10 95 / Super Plus E10 98, \n]                                                                                       1
[\n, Regular/Benzine 91 / Super 95 / Super E10 95 / Regular/Benzine E10 91, \n]                                                             1
[\n, Super 95 / Regular/Benzine 91 / Super E10 95 / Super Plus 98 / Super Plus E10 98 / Regular/Benzine E10 91, \n]                         1
[\n, S

In [296]:
oto.Fuel.str[1].value_counts(dropna = False)

Diesel (Particulate Filter)                                                                                  4315
Super 95                                                                                                     3338
Gasoline                                                                                                     3175
Diesel                                                                                                       2984
Super 95 / Regular/Benzine 91                                                                                 424
                                                                                                             ... 
Super 95 / Regular/Benzine E10 91                                                                               1
Super Plus E10 98                                                                                               1
Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91                                  

In [297]:
oto["fuel_new"] = oto.Fuel.str[1]

In [298]:
diesel_bool = oto["fuel_new"].str.contains("diesel", case = False, regex = True)

In [299]:
lpg_bool = oto["fuel_new"].str.contains("lpg|cng|bio|domestic|electric", case = False, regex = True)

In [301]:
oto.loc[diesel_bool, "fuel_new"] = "Diesel"

In [303]:
oto.loc[lpg_bool, "fuel_new"] = "LPG/CNG"

In [305]:
oto.fuel_new.loc[lambda x : x != "Diesel"][lambda x : x != "LPG/CNG"]

1                                             Gasoline
9                                             Gasoline
11                                            Super 95
12                                  Regular/Benzine 91
13                                            Gasoline
                             ...                      
15908                                         Gasoline
15910                           Regular/Benzine E10 91
15913                                         Super 95
15915    Super 95 / Super Plus 98 (Particulate Filter)
15918                                         Super 95
Name: fuel_new, Length: 8550, dtype: object

In [306]:
oto.fuel_new.loc[lambda x : x != "Diesel"][lambda x : x != "LPG/CNG"].index

Int64Index([    1,     9,    11,    12,    13,    14,    18,    21,    22,    24,
            ...
            15900, 15903, 15905, 15906, 15907, 15908, 15910, 15913, 15915, 15918], dtype='int64', length=8550)

In [307]:
benz = list(oto.fuel_new.loc[lambda x : x != "Diesel"][lambda x : x != "LPG/CNG"].index)

In [308]:
oto.fuel_new.iloc[benz] = "Benzine"

In [309]:
oto.fuel_new.value_counts(dropna = False)

Benzine    8550
Diesel     7299
LPG/CNG      70
Name: fuel_new, dtype: int64

***

### ``'Gears'``

In [310]:
oto.Gears.isnull().sum()/oto.Gears.shape[0]*100

29.599849236761106

In [311]:
oto.Gears.value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n6\n]     5822
NaN         4712
[\n5\n]     3239
[\n7\n]     1908
[\n8\n]      224
[\n9\n]        6
[\n4\n]        2
[\n3\n]        2
[\n1\n]        2
[\n50\n]       1
[\n2\n]        1
Name: Gears, dtype: int64

In [312]:
oto["Gears"] = oto.Gears.str[0].str.strip('\n')

In [313]:
oto.Gears.value_counts(dropna = False)

6      5822
NaN    4712
5      3239
7      1908
8       224
9         6
1         2
4         2
3         2
2         1
50        1
Name: Gears, dtype: int64

In [314]:
oto[oto["Gears"] == "50"]

url    make_model              short_description body_type  price             vat     km registration     hp                            Type Previous Owners Next Inspection Inspection new Warranty null         Make           Model     Offer Number First Registration       Body Color      Paint Type   Upholstery Nr. of Doors Nr. of Seats      Gearing Type  Displacement Cylinders Drive chain                Fuel                                                               Consumption               CO2 Emission Emission Class                                                                                              \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n                                                                                                                                                                                                          \nSafety & Security\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          description   Emission Label Gears Country version Previous_Owner1 Previous_Owner  Inspection_New_Bool next_inspection paint_type  country emission_label                                                                                             Comfort&Convenience  cc_Air conditioning  cc_Air suspension  cc_Armrest  cc_Automatic climate control  cc_Auxiliary heating  cc_Cruise control  cc_Electric Starter  cc_Electric tailgate  cc_Electrical side mirrors  \
14495  https://www.autoscout24.com//offers/renault-clio-limited-2018-tce-75-klima-led-gasoline-black-d14154cc-3f6a-4947-87d6-d92768954315  Renault Clio  LIMITED 2018 TCe 75 Klima/LED    Sedans  10798  VAT deductible  10 km      01/2019  56 kW  [, Pre-registered, , Super 95]           \n1\n             NaN            NaN      NaN   []  \nRenault\n  [\n, Clio, \n]  [\nKL_503764\n]     [\n, 2019, \n]  [\n, Black, \n]  [\nMetallic\n]  [\nCloth\n]      [\n5\n]      [\n5\n]  [\n, Manual, \n]  [\n898 cc\n]       NaN         NaN  [\n, Super 95, \n]  [[5.2 l/100 km (comb)], [6.5 l/100 km (city)], [4.4 l/100 km (country)]]  [\n118 g CO2/km (comb)\n]   [\nEuro 6\n]  [Air conditioning, Cruise control, Electrical side mirrors, Leather steering wheel, Power windows, Start-stop system]                     [USB]        NaN  [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Isofix, LED Daytime Running Lights, Passenger-side airbag, Side airbag, Tire pressure monitoring system, Traction control]  [\n, Sicherheit Airbags:,  , Beifahrerairbag,  , Fahrerairbag,  , Kopfairbags vorne,  , Seitenairbag,  , Sicherheit:,  , ABS,  , Antriebsschlupfregelung (ASR),  , elektr. Stabilitätsprogramm (ESP),  , Geschwindigkeitsbegrenzungsanlage,  , ISOFIX Kindersitzhalterung,  , Kopfstützen im Fonds,  , LED-Tagfahrlicht,  , Reifendruckkontrolle,  , Sommerreifen,  , Tagfahrlicht,  , Traktionskontrolle,  , Komfort:,  , Außenspiegel beheizbar,  , Außenspiegel elektr.,  , Elektr. Fensterheber,  , Fahrersi...  [\n4 (Green)\n]    50   [\nGermany\n]             NaN              1                    0             NaT   Metallic  Germany      4 (Green)  Air conditioning,Cruise control,Electrical side mirrors,Leather steering wheel,Power windows,Start-stop system                    1                  0           0                             0                     0                  1                    0                     0                           1   

       cc_Electrically adjustable seats  cc_Electrically heated windshield  cc_Heads-up display  cc_Heated steering wheel  cc_Hill Holder  cc_Key

In [315]:
oto.Gears.iloc[14495] = "5"

In [316]:
oto.Gears.value_counts(dropna = False)

6      5822
NaN    4712
5      3240
7      1908
8       224
9         6
1         2
4         2
3         2
2         1
Name: Gears, dtype: int64

***

### ``'Make'``

In [317]:
oto.Make.value_counts(dropna = False)

\nOpel\n       7343
\nAudi\n       5712
\nRenault\n    2864
Name: Make, dtype: int64

In [318]:
oto.Make = oto.Make.str.strip('\n')

oto.Make.value_counts()

Opel       7343
Audi       5712
Renault    2864
Name: Make, dtype: int64

***

### ``'Model'``

In [319]:
oto.Model.value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n, A3, \n]          3097
[\n, A1, \n]          2614
[\n, Insignia, \n]    2598
[\n, Astra, \n]       2526
[\n, Corsa, \n]       2219
[\n, Clio, \n]        1839
[\n, Espace, \n]       991
[\n, Duster, \n]        34
[\n, A2, \n]             1
Name: Model, dtype: int64

In [320]:
oto.Model = oto.Model.str[1] 

oto.Model.value_counts()

A3          3097
A1          2614
Insignia    2598
Astra       2526
Corsa       2219
Clio        1839
Espace       991
Duster        34
A2             1
Name: Model, dtype: int64

***

### ``'Nr. of Doors'``

In [321]:
oto["Nr. of Doors"].isnull().sum()/oto["Nr. of Doors"].shape[0]*100

1.3317419435894216

In [322]:
oto['Nr. of Doors'].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n5\n]    11575
[\n4\n]     3079
[\n3\n]      832
[\n2\n]      219
NaN          212
[\n7\n]        1
[\n1\n]        1
Name: Nr. of Doors, dtype: int64

In [323]:
oto['Nr. of Doors'].str[0].str.strip('\n').value_counts(dropna=False)

5      11575
4       3079
3        832
2        219
NaN      212
1          1
7          1
Name: Nr. of Doors, dtype: int64

In [324]:
oto['nr_doors'] = oto['Nr. of Doors'].str[0].str.strip('\n') 

oto.nr_doors.value_counts(dropna = False)

5      11575
4       3079
3        832
2        219
NaN      212
1          1
7          1
Name: nr_doors, dtype: int64

***

### 'Nr. of Seats'

In [325]:
oto['Nr. of Seats'].isnull().sum()/oto['Nr. of Seats'].shape[0]*100

6.137320183428607

In [326]:
oto['Nr. of Seats'].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n5\n]    13336
[\n4\n]     1125
NaN          977
[\n7\n]      362
[\n2\n]      116
[\n6\n]        2
[\n3\n]        1
Name: Nr. of Seats, dtype: int64

In [327]:
oto['Nr. of Seats'].str[0].str.strip('\n').value_counts(dropna = False)

5      13336
4       1125
NaN      977
7        362
2        116
6          2
3          1
Name: Nr. of Seats, dtype: int64

In [328]:
oto['nr_seats'] = oto['Nr. of Seats'].str[0].str.strip('\n')

oto.nr_seats.value_counts(dropna = False)

5      13336
4       1125
NaN      977
7        362
2        116
6          2
3          1
Name: nr_seats, dtype: int64

***

### 'Offer Number'

In [329]:
oto["Offer Number"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                       3175
[\nXJ38068\n]               27
[\nHM53619\n]               27
[\nLT67679\n]               27
[\nJV03654\n]               27
                          ... 
[\nE84_474_6130_158\n]       1
[\n101\n]                    1
[\n418394\n]                 1
[\nrv290009\n]               1
[\nG02394\n]                 1
Name: Offer Number, Length: 11441, dtype: int64

In [330]:
oto.drop("Offer Number", axis = 1, inplace = True)

***

### 'Type'

In [331]:
oto.Type.isnull().sum()/oto.Type.shape[0]*100

0.012563603241409635

In [332]:
oto['Type'].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[, Used, , Diesel (Particulate Filter)]                                                                                  3475
[, Used, , Diesel]                                                                                                       2516
[, Used, , Gasoline]                                                                                                     2367
[, Used, , Super 95]                                                                                                     1818
[, Pre-registered, , Super 95]                                                                                            500
                                                                                                                         ... 
[, Used, , Regular/Benzine E10 91 / Super E10 95 / Super Plus E10 98 / Super Plus 98 / Super 95 / Regular/Benzine 91]       1
[, Used, , Regular/Benzine E10 91 / Regular/Benzine 91 / Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98] 

In [333]:
oto.Type.str[1].value_counts(dropna = False)

Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
NaN                   2
Name: Type, dtype: int64

In [334]:
oto.Type = oto['Type'].str[1]

oto.Type.value_counts(dropna = False)

Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
NaN                   2
Name: Type, dtype: int64

***

### 'Upholstery'

In [335]:
oto.Upholstery.isnull().sum()/oto.Upholstery.shape[0]*100

23.368302029021923

In [336]:
oto.Upholstery.value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\nCloth, Black\n]           5821
NaN                          3720
[\nPart leather, Black\n]    1121
[\nCloth\n]                  1005
[\nCloth, Grey\n]             891
[\nCloth, Other\n]            639
[\nFull leather, Black\n]     575
[\nBlack\n]                   491
[\nGrey\n]                    273
[\nOther, Other\n]            182
[\nPart leather\n]            140
[\nFull leather\n]            139
[\nFull leather, Brown\n]     116
[\nPart leather, Grey\n]      116
[\nOther, Black\n]            110
[\nFull leather, Other\n]      72
[\nFull leather, Grey\n]       67
[\nPart leather, Other\n]      65
[\nOther\n]                    56
[\nPart leather, Brown\n]      50
[\nalcantara, Black\n]         47
[\nVelour, Black\n]            36
[\nFull leather, Beige\n]      36
[\nCloth, Brown\n]             28
[\nVelour\n]                   16
[\nOther, Grey\n]              15
[\nCloth, Beige\n]             13
[\nCloth, Blue\n]              12
[\nBrown\n]                    12
[\nVelour, Gre

In [337]:
oto.Upholstery = oto.Upholstery.str[0].str.strip('\n')

In [338]:
oto.Upholstery.value_counts(dropna = False)

Cloth, Black           5821
NaN                    3720
Part leather, Black    1121
Cloth                  1005
Cloth, Grey             891
Cloth, Other            639
Full leather, Black     575
Black                   491
Grey                    273
Other, Other            182
Part leather            140
Full leather            139
Full leather, Brown     116
Part leather, Grey      116
Other, Black            110
Full leather, Other      72
Full leather, Grey       67
Part leather, Other      65
Other                    56
Part leather, Brown      50
alcantara, Black         47
Velour, Black            36
Full leather, Beige      36
Cloth, Brown             28
Velour                   16
Other, Grey              15
Cloth, Beige             13
Cloth, Blue              12
Brown                    12
Cloth, White              8
Velour, Grey              8
alcantara, Grey           6
Cloth, Red                5
Other, Yellow             4
Part leather, Red         3
Beige               

***

### 'Warranty'

In [339]:
oto.Warranty.isnull().sum()/oto.Warranty.shape[0]*100

34.047364784220115

In [340]:
oto.Warranty.isnull().sum()

5420

In [341]:
oto.Warranty.value_counts(dropna=False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n72 months\n, \n142 g CO2/km (comb)\n]                                                                1
[\n20 months\n, \n120 g CO2/km (comb)\n]                                                                1
[\n1 months\n, \nEuro 6\n]                                                                              2
[\n60 months\n, \n137 g CO2/km (comb)\n]                                                                3
[\n72 months\n, \n140 g CO2/km (comb)\n]                                                                1
[\n, \n, \n107 g CO2/km (comb)\n]                                                                      25
[\n60 months\n, \n102 g CO2/km (comb)\n]                                                                9
[\n, \n, \n, 5.9 l/100 km (comb), \n, 7.5 l/100 km (city), \n, 5 l/100 km (country), \n]                3
[\n60 months\n, \n, 5.9 l/100 km (comb), \n, 7.5 l/100 km (city), \n, 4.9 l/100 km (country), \n]       1
[\n24 months\n, \n124 g CO2/km (comb)\n]      

In [342]:
oto.Warranty.value_counts(dropna=False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n24 months\n, \n140 g CO2/km (comb)\n]                                                             22
[\n12 months\n, \n129 g CO2/km (comb)\n]                                                              3
[\n12 months\n, \n119 g CO2/km (comb)\n]                                                             24
[\n72 months\n, \n151 g CO2/km (comb)\n]                                                              2
[\n36 months\n, \n4 (Green)\n]                                                                       30
[\n40 months\n]                                                                                       1
[\n12 months\n, \n, 6.7 l/100 km (comb), \n, 8.6 l/100 km (city), \n, 5.6 l/100 km (country), \n]     1
[\n11 months\n, \nEuro 6\n]                                                                           1
[\n, \n, \n161 g CO2/km (comb)\n]                                                                     1
[\n25 months\n, \nEuro 6\n]                                     

In [344]:
warranty_list = ["".join(item).strip() if type(item) == list else item for item in oto["Warranty"]]

In [345]:
oto["warranty_month"] = pd.DataFrame(warranty_list)

In [346]:
oto.warranty_month.value_counts(dropna = False).sample(55)

99 g CO2/km (comb)                                                               30
40 months                                                                         1
72 months\n\n116 g CO2/km (comb)                                                  1
60 months\n\n142 g CO2/km (comb)                                                  4
12 months\n\n101 g CO2/km (comb)                                                 14
60 months\n\n91 g CO2/km (comb)                                                   2
149 g CO2/km (comb)                                                               5
60 months\n\n148 g CO2/km (comb)                                                  1
34 months\n\nEuro 6                                                               2
24 months\n\nEuro 6d                                                              2
12 months\n\n95 g CO2/km (comb)                                                  21
48 months\n\n4 (Green)                                                      

In [347]:
oto.warranty_month.value_counts(dropna = False).sample(55)

72 months\n\n133 g CO2/km (comb)                                                    1
24 months\n\n92 g CO2/km (comb)                                                     2
36 months\n\n104 g CO2/km (comb)                                                    4
36 months\n\n7.4 l/100 km (comb)\n9.6 l/100 km (city)\n6 l/100 km (country)         1
36 months\n\n102 g CO2/km (comb)                                                    4
18 months\n\n120 g CO2/km (comb)                                                    3
60 months\n\n115 g CO2/km (comb)                                                    2
161 g CO2/km (comb)                                                                 1
4.7 l/100 km (comb)\n5.5 l/100 km (city)\n4.1 l/100 km (country)                    1
157 g CO2/km (comb)                                                                 7
20 months\n\n139 g CO2/km (comb)                                                    1
12 months\n\n105 g CO2/km (comb)                      

- There are several numeric values in the same line
- In order to select months from among the other numeric values, we should use the syntax below.
- Firstly, we will select ``"dd months"``
- Secondly, we replace all chars other than numeric

In [349]:
oto.warranty_month.str.extract("(\d\d months|\d months)")

0
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
...          ...
15914  24 months
15915        NaN
15916        NaN
15917        NaN
15918        NaN

[15919 rows x 1 columns]

In [350]:
oto["warranty_month"] = oto.warranty_month.str.extract("(\d\d months|\d months)")

In [351]:
oto.warranty_month.value_counts(dropna = False)

NaN          11066
12 months     2594
24 months     1118
60 months      401
36 months      279
48 months      149
6 months       125
72 months       59
3 months        33
23 months       11
18 months       10
20 months        7
25 months        6
2 months         5
16 months        4
50 months        4
26 months        4
34 months        3
13 months        3
4 months         3
19 months        3
1 months         3
9 months         2
45 months        2
22 months        2
17 months        2
28 months        2
46 months        2
21 months        2
11 months        2
14 months        2
15 months        1
47 months        1
7 months         1
8 months         1
49 months        1
33 months        1
10 months        1
56 months        1
40 months        1
65 months        1
30 months        1
Name: warranty_month, dtype: int64

In [353]:
oto.drop(["Warranty", "warranty_month"], axis = 1, inplace = True)

- It has too many missing values so, it will not effect the result if we drop it.

***

### ``'description'``

In [354]:
oto.description.head()

0    [\n, Sicherheit:,  , Deaktivierung für Beifahrer-Airbag,  , ESC mit elektronischer Quersperre,  , Tagfahrlicht,  , Reifendruck-Kontrollanzeige,  , Kopfairbag-System mit Seiten-Airbags vorn,  , Sicherheitslenksäule, Assistenzsysteme:,  , Berganfahrassistent, Komfort:,  , Scheinwerferreinigung,  , Xenon plus inklusive Scheinwerfer-Reinigungsanlage,  , Scheinwerfer-Reinigungsanlage,  , Einparkhilfe hinten,  , Licht-/Regensensor,  , Funkfernbedienung,  , Elektrische Luftzusatzheizung, Interieur:...
1                                                                                                                                                                                                                                                                                                                                                                                                           [\nLangstreckenfahrzeug daher die hohe Kilometerleistung. , Bremsen neu bei 62000 km. , Gut gepfleg

In [355]:
oto.drop('description', axis=1, inplace = True)

***

### 'hp'

In [356]:
oto.hp.value_counts(dropna = False)

85 kW     2542
66 kW     2122
81 kW     1402
100 kW    1308
110 kW    1112
          ... 
133 kW       1
84 kW        1
195 kW       1
239 kW       1
137 kW       1
Name: hp, Length: 81, dtype: int64

In [357]:
oto.hp.isnull().sum()

0

In [358]:
oto.hp.value_counts(dropna=False).sample(55)

168 kW       3
63 kW        2
135 kW      24
74 kW       81
67 kW       40
100 kW    1308
143 kW       2
65 kW        4
44 kW        1
165 kW     194
127 kW       2
294 kW      18
90 kW        4
40 kW        2
93 kW        3
123 kW       1
96 kW       72
55 kW      569
54 kW      276
112 kW       7
98 kW        3
133 kW       1
137 kW       1
167 kW       2
4 kW         1
101 kW      47
52 kW       22
103 kW     253
125 kW     707
86 kW        2
110 kW    1112
164 kW      27
60 kW      160
89 kW        2
78 kW       20
53 kW        2
71 kW       59
155 kW       6
119 kW      30
146 kW      18
120 kW       8
- kW        88
154 kW      39
92 kW      466
104 kW       8
191 kW       7
117 kW       6
149 kW       3
51 kW      695
66 kW     2122
228 kW       2
57 kW       10
81 kW     1402
122 kW      35
195 kW       1
Name: hp, dtype: int64

In [359]:
oto.hp.value_counts(dropna=False).sample(55)

101 kW      47
60 kW      160
93 kW        3
168 kW       3
- kW        88
155 kW       6
103 kW     253
100 kW    1308
119 kW      30
76 kW        4
147 kW     380
1 kW        20
81 kW     1402
71 kW       59
132 kW       1
54 kW      276
44 kW        1
270 kW       2
162 kW      98
115 kW       1
120 kW       8
104 kW       8
239 kW       1
146 kW      18
121 kW     392
53 kW        2
117 kW       6
133 kW       1
80 kW        3
63 kW        2
228 kW       2
195 kW       1
135 kW      24
74 kW       81
123 kW       1
149 kW       3
125 kW     707
294 kW      18
184 kW       5
150 kW       2
88 kW      177
65 kW        4
110 kW    1112
85 kW     2542
98 kW        3
122 kW      35
66 kW     2122
86 kW        2
4 kW         1
78 kW       20
51 kW      695
143 kW       2
87 kW      232
55 kW      569
84 kW        1
Name: hp, dtype: int64

In [360]:
oto.hp.unique()

array(['66 kW', '141 kW', '85 kW', '70 kW', '92 kW', '112 kW', '60 kW',
       '71 kW', '67 kW', '110 kW', '93 kW', '147 kW', '86 kW', '140 kW',
       '87 kW', '- kW', '81 kW', '82 kW', '135 kW', '132 kW', '100 kW',
       '96 kW', '162 kW', '150 kW', '294 kW', '228 kW', '270 kW',
       '137 kW', '9 kW', '133 kW', '77 kW', '101 kW', '78 kW', '103 kW',
       '1 kW', '74 kW', '118 kW', '84 kW', '88 kW', '80 kW', '76 kW',
       '149 kW', '44 kW', '51 kW', '55 kW', '52 kW', '63 kW', '40 kW',
       '65 kW', '75 kW', '125 kW', '120 kW', '184 kW', '239 kW', '121 kW',
       '143 kW', '191 kW', '89 kW', '195 kW', '127 kW', '122 kW',
       '154 kW', '155 kW', '104 kW', '123 kW', '146 kW', '90 kW', '53 kW',
       '54 kW', '56 kW', '164 kW', '4 kW', '163 kW', '57 kW', '119 kW',
       '165 kW', '117 kW', '115 kW', '98 kW', '168 kW', '167 kW'],
      dtype=object)

In [363]:
oto.replace({"hp" : {" kW" : "", "-" : "0"}}, regex = True, inplace = True)

In [364]:
oto["hp_kw"] = pd.to_numeric(oto.hp)

In [365]:
oto.hp_kw.value_counts(dropna = False)

85     2542
66     2122
81     1402
100    1308
110    1112
       ... 
163       1
123       1
115       1
75        1
239       1
Name: hp_kw, Length: 81, dtype: int64

***

### ``'km'``

In [366]:
oto.km.isnull().sum()

0

In [367]:
oto.km.value_counts(dropna = False)

10 km        1045
- km         1024
1 km          367
5 km          170
50 km         148
             ... 
12,260 km       1
42,906 km       1
95,300 km       1
30,968 km       1
22,837 km       1
Name: km, Length: 6690, dtype: int64

- There are "-" values which means ``NaN``s. We can not accept these values as 0 km.

In [368]:
oto[oto["km"] == "- km"]["register_age"].value_counts(dropna = False)

NaN    838
1.0    147
2.0     38
3.0      1
Name: register_age, dtype: int64

In [369]:
oto.replace({"km" : {" km" : "", "," : "", "-" : np.nan}}, regex = True, inplace = True)

In [370]:
oto.km = pd.to_numeric(oto.km)

In [371]:
oto.km.value_counts(dropna = False)

10.0       1045
NaN        1024
1.0         367
5.0         170
50.0        148
           ... 
8329.0        1
267.0         1
1060.0        1
73652.0       1
49320.0       1
Name: km, Length: 6690, dtype: int64

***

### ``'make_model' ``

In [372]:
oto.make_model.isnull().sum()

0

In [373]:
oto.make_model.value_counts(dropna=False) 

Audi A3           3097
Audi A1           2614
Opel Insignia     2598
Opel Astra        2526
Opel Corsa        2219
Renault Clio      1839
Renault Espace     991
Renault Duster      34
Audi A2              1
Name: make_model, dtype: int64

In [374]:
oto.drop(["Make", "Model"], axis = 1, inplace = True)

***

### ``'null'``

In [375]:
oto.null.isnull().sum()

0

In [376]:
oto.null.value_counts(dropna=False) 

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[]    15919
Name: null, dtype: int64

In [377]:
oto.drop("null", axis = 1, inplace = True)

***

### ``'registration'``

In [379]:
oto.registration.isnull().sum()

0

In [380]:
oto.registration.value_counts(dropna = False) 

-/-        1597
03/2018     695
02/2019     585
05/2018     572
03/2019     543
01/2019     541
04/2018     541
02/2018     539
03/2016     536
04/2016     532
06/2018     532
01/2018     511
04/2019     506
02/2016     472
03/2017     471
05/2016     459
06/2016     452
05/2019     440
06/2017     409
05/2017     404
07/2018     396
04/2017     380
01/2016     376
02/2017     368
01/2017     306
08/2018     285
06/2019     224
07/2017     215
11/2017     180
07/2016     176
10/2016     160
10/2017     154
09/2017     149
11/2016     142
09/2016     141
09/2018     141
12/2016     134
12/2017     123
08/2017     114
11/2018     110
12/2018     103
10/2018      97
08/2016      94
07/2019       6
09/2019       5
08/2019       1
11/2019       1
12/2019       1
Name: registration, dtype: int64

In [381]:
oto.drop("registration", axis = 1, inplace = True)

***

### ``'short_description'``

In [382]:
oto.short_description.isnull().sum()

46

In [383]:
oto.short_description.value_counts(dropna = False) 

SPB 1.6 TDI 116 CV S tronic Sport                 64
NaN                                               46
1.4 66kW (90CV) Selective                         40
MOVE KLIMA CD USB ALLWETTER BLUETOOTH             38
SPB 30 TDI S tronic Business                      35
                                                  ..
s line SPB 30 TDI S tronic Business (364) GR       1
30 Sportback 1.0 TFSI Sport Klima Sitzh.           1
1.4 ST Selection KLIMA BLUETOOTH                   1
Limousine Sport MJ19 (D9) 35 TFSI                  1
Sportback 1.4TFSI S tronic/Navi/APS Navi Leder     1
Name: short_description, Length: 10002, dtype: int64

In [384]:
oto.drop("short_description", axis = 1, inplace = True)

***

### ``'url'``

In [385]:
oto.url.value_counts(dropna = False)

https://www.autoscout24.com//offers/opel-insignia-st-1-6-ecotec-edition-start-stop-system-aut-diesel-silver-8975ad96-474b-40f0-bbc9-42c304d56c86      1
https://www.autoscout24.com//offers/audi-a3-sportback-1-6-tdi-facelift-navi-xenon-alus-e6-diesel-blue-62d3865f-32e5-45fd-9f94-dd7593a30db2            1
https://www.autoscout24.com//offers/opel-insignia-1-6-turbo-dynamic-led-kamera-einparkass-gasoline-grey-c4c0625c-789d-4fb3-a1be-585d68b9fbd2          1
https://www.autoscout24.com//offers/opel-astra-5-serie-1-6-cdti-110cv-start-stop-sports-tourer-d-diesel-black-e13cca86-2c13-45d3-a125-a478801e7351    1
https://www.autoscout24.com//offers/audi-a3-new-spbk-30-tdi-1-6-116cv-my-20-diesel-white-73e329bb-5a34-4f16-a635-42889eaee599                         1
                                                                                                                                                     ..
https://www.autoscout24.com//offers/opel-corsa-1-4-automatik-120-jahre-gasoline-silver-3

In [386]:
oto.drop('url', axis = 1, inplace = True) 

***

### ``'vat'``

In [387]:
oto.vat.isnull().sum()/oto.vat.shape[0]*100

28.349770714240847

In [388]:
oto.vat.value_counts(dropna = False) 

VAT deductible      10980
NaN                  4513
Price negotiable      426
Name: vat, dtype: int64

***

### ``'price'``

- This is our target variable which we try to predict..

In [389]:
oto.price.isnull().sum()

0

In [390]:
oto.price.sort_values()

8594        13
8828       120
6066       255
8829       331
8827      4950
         ...  
15828    64332
3587     64900
3649     67600
15826    68320
3648     74600
Name: price, Length: 15919, dtype: int64

In [391]:
oto.price.value_counts(dropna = False)

14990    154
15990    151
10990    139
15900    106
17990    102
        ... 
48490      1
36180      1
40745      1
9545       1
34815      1
Name: price, Length: 2956, dtype: int64

In [392]:
print(list(oto.columns))

['make_model', 'body_type', 'price', 'vat', 'km', 'hp', 'Type', 'Previous Owners', 'Next Inspection', 'Inspection new', 'First Registration', 'Body Color', 'Paint Type', 'Upholstery', 'Nr. of Doors', 'Nr. of Seats', 'Gearing Type', 'Displacement', 'Cylinders', 'Drive chain', 'Fuel', 'Consumption', 'CO2 Emission', 'Emission Class', '\nComfort & Convenience\n', '\nEntertainment & Media\n', '\nExtras\n', '\nSafety & Security\n', 'Emission Label', 'Gears', 'Country version', 'Previous_Owner1', 'Previous_Owner', 'Inspection_New_Bool', 'next_inspection', 'paint_type', 'country', 'emission_label', 'Comfort&Convenience', 'cc_Air conditioning', 'cc_Air suspension', 'cc_Armrest', 'cc_Automatic climate control', 'cc_Auxiliary heating', 'cc_Cruise control', 'cc_Electric Starter', 'cc_Electric tailgate', 'cc_Electrical side mirrors', 'cc_Electrically adjustable seats', 'cc_Electrically heated windshield', 'cc_Heads-up display', 'cc_Heated steering wheel', 'cc_Hill Holder', 'cc_Keyless central door 

### Now, it is time to drop repeated columns we have.

In [393]:
current_clmn = list(oto.columns)

In [395]:
drop_columns = ['Previous Owners', 'Next Inspection', 'Inspection new', 'First Registration', 'Body Color', 'Paint Type', 
 'Nr. of Doors', 'Nr. of Seats', 'Gearing Type', 'Displacement', 'Drive chain', 'Fuel', 'Consumption', 
 'CO2 Emission', 'Emission Class', '\nComfort & Convenience\n', '\nEntertainment & Media\n', '\nExtras\n', 
 '\nSafety & Security\n', 'Emission Label', 'Country version', 'Previous_Owner1', 'Comfort&Convenience', 
 'Entertainment&Media', 'extra', 'Safe&Secure', "hp"]

In [396]:
oto1 = oto.drop(drop_columns, axis = 1)

In [397]:
oto1.shape

(15919, 121)

In [398]:
oto1.columns = oto1.columns.str.lower()

In [399]:
list(oto1.columns)

['make_model',
 'body_type',
 'price',
 'vat',
 'km',
 'type',
 'upholstery',
 'cylinders',
 'gears',
 'previous_owner',
 'inspection_new_bool',
 'next_inspection',
 'paint_type',
 'country',
 'emission_label',
 'cc_air conditioning',
 'cc_air suspension',
 'cc_armrest',
 'cc_automatic climate control',
 'cc_auxiliary heating',
 'cc_cruise control',
 'cc_electric starter',
 'cc_electric tailgate',
 'cc_electrical side mirrors',
 'cc_electrically adjustable seats',
 'cc_electrically heated windshield',
 'cc_heads-up display',
 'cc_heated steering wheel',
 'cc_hill holder',
 'cc_keyless central door lock',
 'cc_leather seats',
 'cc_leather steering wheel',
 'cc_light sensor',
 'cc_lumbar support',
 'cc_massage seats',
 'cc_multi-function steering wheel',
 'cc_navigation system',
 'cc_panorama roof',
 'cc_park distance control',
 'cc_parking assist system camera',
 'cc_parking assist system self-steering',
 'cc_parking assist system sensors front',
 'cc_parking assist system sensors rear'

In [ ]:
oto1.to_csv("scout_car_precleaned.csv", index = False)

## End of this Project. Next step will be :
- Handling with Missing Values and Outliers,
- Continue to clean DataSet.
- Make the DataSet ready to go into ML Models.